#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成改编自社媒考研数学题目的JSON文件"""

import json

questions = []

# ========== 高数 60道 ==========
# 极限 (12道)
questions.extend([
    {"id": "soc_gs_001", "subject": "高数", "type": "选择", "difficulty": 2, "content": "求极限 $\\lim_{x \\to 0} \\frac{\\sin 3x - 3x}{x^{3}}$ 的值。", "options": ["A. $-\\frac{9}{2}$", "B. $-\\frac{1}{2}$", "C. $\\frac{9}{2}$", "D. $0$"], "answer": "A", "analysis": "利用泰勒展开 $\\sin 3x = 3x - \\frac{(3x)^{3}}{6} + o(x^{3}) = 3x - \\frac{9x^{3}}{2} + o(x^{3})$。故 $\\sin 3x - 3x = -\\frac{9x^{3}}{2} + o(x^{3})$，除以 $x^{3}$ 得 $-\\frac{9}{2}$。选 A。", "source": "自建题目", "tags": ["极限", "泰勒展开"], "origin": "改编自CSDN考研数学极限题，原题用sin x，改为sin 3x"},
    {"id": "soc_gs_002", "subject": "高数", "type": "选择", "difficulty": 1, "content": "当 $x \\to 0$ 时，下列函数中与 $2x$ 等价无穷小的是（ ）。", "options": ["A. $1 - \\cos x$", "B. $\\ln(1+2x)$", "C. $\\sin x^{2}$", "D. $\\sqrt{1+x} - 1$"], "answer": "B", "analysis": "$x \\to 0$ 时：$1-\\cos x \\sim \\frac{x^{2}}{2}$（二阶）；$\\ln(1+2x) \\sim 2x$（一阶，与 $2x$ 等价）；$\\sin x^{2} \\sim x^{2}$（二阶）；$\\sqrt{1+x}-1 \\sim \\frac{x}{2}$（一阶但不等价于 $2x$）。选 B。", "source": "自建题目", "tags": ["极限", "等价无穷小"], "origin": "改编自等价无穷小比较题，原题与x比较，改为与2x比较"},
    {"id": "soc_gs_003", "subject": "高数", "type": "选择", "difficulty": 3, "content": "函数 $f(x) = \\frac{x^{2} - 2x}{|x|(x-2)}$ 的间断点个数为（ ）。", "options": ["A. $1$ 个", "B. $2$ 个", "C. $3$ 个", "D. $0$ 个"], "answer": "B", "analysis": "可疑间断点 $x=0$ 和 $x=2$。$x>0$ 时 $|x|=x$，$f=\\frac{x^{2}-2x}{x(x-2)}=1$；$x<0$ 时 $|x|=-x$，$f=\\frac{x^{2}-2x}{-x(x-2)}=-1$。故 $x=0$ 处左右极限分别为 $-1$ 和 $1$，为跳跃间断点。$x=2$ 处极限为 $1$ 但无定义，为可去间断点。共 $2$ 个。", "source": "自建题目", "tags": ["极限", "连续性", "间断点"], "origin": "改编自间断点判断题，原题x²-x改为x²-2x"},
    {"id": "soc_gs_004", "subject": "高数", "type": "填空", "difficulty": 2, "content": "$\\lim_{x \\to 0} \\frac{e^{2x} - 1 - 2x}{x^{2}} = $ ____。", "options": None, "answer": "$2$", "analysis": "用泰勒展开 $e^{2x} = 1 + 2x + \\frac{(2x)^{2}}{2} + o(x^{2}) = 1 + 2x + 2x^{2} + o(x^{2})$。故 $e^{2x} - 1 - 2x = 2x^{2} + o(x^{2})$，除以 $x^{2}$ 得 $2$。", "source": "自建题目", "tags": ["极限", "泰勒展开"], "origin": "改编自e^x极限题，改为e^{2x}"},
    {"id": "soc_gs_005", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求极限 $\\lim_{x \\to 0^{+}} (e^{2x} - 1)^{\\frac{1}{\\ln x}}$。", "options": None, "answer": "$e$", "analysis": "这是 $1^{\\infty}$ 型未定式，取对数。设 $y = (e^{2x} - 1)^{\\frac{1}{\\ln x}}$，则 $\\ln y = \\frac{\\ln(e^{2x} - 1)}{\\ln x}$。$x \\to 0^{+}$ 时 $e^{2x} - 1 \\sim 2x$，故 $\\ln(e^{2x}-1) \\sim \\ln(2x) = \\ln 2 + \\ln x$。$\\lim \\ln y = \\lim \\frac{\\ln 2 + \\ln x}{\\ln x} = 1$。故原极限 $= e^{1} = e$。", "source": "自建题目", "tags": ["极限", "未定式"], "origin": "改编自CSDN极限题，e^x改为e^{2x}"},
    {"id": "soc_gs_006", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $x \\to 0$ 时，$(1+2ax^{2})^{\\frac{1}{3}} - 1$ 与 $\\sin x^{2}$ 是等价无穷小，则 $a = $（ ）。", "options": ["A. $\\frac{1}{3}$", "B. $1$", "C. $\\frac{3}{2}$", "D. $\\frac{1}{2}$"], "answer": "C", "analysis": "$(1+2ax^{2})^{\\frac{1}{3}} - 1 \\sim \\frac{1}{3} \\cdot 2ax^{2} = \\frac{2a}{3}x^{2}$。$\\sin x^{2} \\sim x^{2}$。等价要求 $\\frac{2a}{3} = 1$，故 $a = \\frac{3}{2}$。选 C。", "source": "自建题目", "tags": ["极限", "等价无穷小"], "origin": "改编自等价无穷小参数题，系数调整"},
    {"id": "soc_gs_007", "subject": "高数", "type": "解答", "difficulty": 4, "content": "设 $x_{1} = 2$，$x_{n+1} = 1 + \\frac{2}{1+x_{n}}$（$n=1,2,\\ldots$），证明 $\\lim_{n \\to \\infty} x_{n}$ 存在并求其值。", "options": None, "answer": "$\\sqrt{3}$", "analysis": "设极限为 $L$，则 $L = 1 + \\frac{2}{1+L}$，即 $L(1+L) = (1+L) + 2$，化简 $L^{2} = 3$，$L = \\sqrt{3}$（舍负）。可用压缩映射证明收敛：$f(x)=1+\\frac{2}{1+x}$，$|f'(x)|=\\frac{2}{(1+x)^{2}}$，当 $x \\geq 2$ 时 $|f'(x)| \\leq \\frac{2}{9} < 1$，故为压缩映射，迭代收敛于唯一不动点 $\\sqrt{3}$。", "source": "自建题目", "tags": ["极限", "数列收敛"], "origin": "改编自递推数列极限题，参数调整"},
    {"id": "soc_gs_008", "subject": "高数", "type": "填空", "difficulty": 3, "content": "设 $f(x) = \\begin{cases} \\frac{\\sin 2x}{x}, & x \\neq 0 \\\\ a, & x=0 \\end{cases}$ 在 $x=0$ 处连续，则 $a = $ ____。", "options": None, "answer": "$2$", "analysis": "连续要求 $f(0) = \\lim_{x \\to 0} f(x) = \\lim_{x \\to 0} \\frac{\\sin 2x}{x} = 2$。故 $a = 2$。这是重要极限 $\\lim_{x \\to 0} \\frac{\\sin kx}{x} = k$ 的直接应用。", "source": "自建题目", "tags": ["极限", "连续性"], "origin": "改编自sin(x)/x连续性题，改为sin(2x)/x"},
    {"id": "soc_gs_009", "subject": "高数", "type": "填空", "difficulty": 3, "content": "$\\lim_{x \\to 0} (1+3x)^{\\frac{1}{x}} = $ ____。", "options": None, "answer": "$e^{3}$", "analysis": "这是重要极限 $\\lim_{x \\to 0} (1+kx)^{\\frac{1}{x}} = e^{k}$ 的应用。这里 $k=3$，故极限 $= e^{3}$。", "source": "自建题目", "tags": ["极限", "重要极限"], "origin": "改编自重要极限题"},
    {"id": "soc_gs_010", "subject": "高数", "type": "填空", "difficulty": 3, "content": "$\\lim_{x \\to 0} \\frac{\\tan 2x - \\sin 2x}{x^{3}} = $ ____。", "options": None, "answer": "$4$", "analysis": "$\\tan 2x - \\sin 2x = \\sin 2x \\cdot \\frac{1-\\cos 2x}{\\cos 2x}$。$x \\to 0$ 时 $\\sin 2x \\sim 2x$，$1-\\cos 2x \\sim \\frac{(2x)^{2}}{2} = 2x^{2}$，$\\cos 2x \\to 1$。故原式 $\\sim \\frac{2x \\cdot 2x^{2}}{x^{3}} = 4$。", "source": "自建题目", "tags": ["极限", "等价无穷小"], "origin": "改编自tan x - sin x极限题，改为tan 2x"},
    {"id": "soc_gs_011", "subject": "高数", "type": "选择", "difficulty": 2, "content": "函数 $f(x) = \\frac{x^{2}-4}{x-2}$ 在 $x=2$ 处的可去间断点处补充定义 $f(2) = $（ ）可使函数连续。", "options": ["A. $0$", "B. $2$", "C. $4$", "D. $\\infty$"], "answer": "C", "analysis": "$\\lim_{x \\to 2} \\frac{x^{2}-4}{x-2} = \\lim_{x \\to 2} (x+2) = 4$。故补充 $f(2)=4$ 可使函数连续。选 C。", "source": "自建题目", "tags": ["极限", "连续性", "可去间断点"], "origin": "改编自可去间断点题"},
    {"id": "soc_gs_012", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求 $\\lim_{x \\to 0} \\frac{e^{x^{2}} - 1 - x^{2}}{x^{4}}$。", "options": None, "answer": "$\\frac{1}{2}$", "analysis": "泰勒展开 $e^{x^{2}} = 1 + x^{2} + \\frac{x^{4}}{2} + o(x^{4})$。故 $e^{x^{2}} - 1 - x^{2} = \\frac{x^{4}}{2} + o(x^{4})$，除以 $x^{4}$ 得 $\\frac{1}{2}$。", "source": "自建题目", "tags": ["极限", "泰勒展开"], "origin": "改编自泰勒展开极限题"},
])

# 导数与中值定理 (10道)
questions.extend([
    {"id": "soc_gs_013", "subject": "高数", "type": "选择", "difficulty": 2, "content": "设 $f(x)$ 在 $x=0$ 处可导，且 $f(0)=0$，则 $\\lim_{x \\to 0} \\frac{f(2x)}{x} = $（ ）。", "options": ["A. $0$", "B. $2f'(0)$", "C. $f'(0)$", "D. $\\frac{f'(0)}{2}$"], "answer": "B", "analysis": "由导数定义 $f'(0) = \\lim_{x \\to 0} \\frac{f(x)}{x}$。故 $\\lim_{x \\to 0} \\frac{f(2x)}{x} = 2 \\lim_{x \\to 0} \\frac{f(2x)}{2x} = 2f'(0)$。选 B。", "source": "自建题目", "tags": ["导数", "导数定义"], "origin": "改编自导数定义极限题，f(x)改为f(2x)"},
    {"id": "soc_gs_014", "subject": "高数", "type": "填空", "difficulty": 2, "content": "设 $y = \\ln(1+2x^{2})$，则 $dy = $ ____。", "options": None, "answer": "$\\frac{4x}{1+2x^{2}} dx$", "analysis": "由复合函数求导 $y' = \\frac{1}{1+2x^{2}} \\cdot (1+2x^{2})' = \\frac{4x}{1+2x^{2}}$。故 $dy = \\frac{4x}{1+2x^{2}} dx$。", "source": "自建题目", "tags": ["导数", "复合函数求导"], "origin": "改编自ln(1+x²)求导题，改为ln(1+2x²)"},
    {"id": "soc_gs_015", "subject": "高数", "type": "解答", "difficulty": 4, "content": "设 $f(x)$ 在 $[0,1]$ 上连续，在 $(0,1)$ 内可导，$f(0)=0$，$f(1)=2$。证明：存在 $\\xi \\in (0,1)$ 使 $f'(\\xi) = 4\\xi$。", "options": None, "answer": "见解析", "analysis": "构造辅助函数 $F(x) = f(x) - 2x^{2}$。则 $F(0) = 0$，$F(1) = 2 - 2 = 0$。$F(x)$ 在 $[0,1]$ 连续，$(0,1)$ 可导，由罗尔定理存在 $\\xi \\in (0,1)$ 使 $F'(\\xi)=0$。$F'(x) = f'(x) - 4x$，故 $f'(\\xi) = 4\\xi$。", "source": "自建题目", "tags": ["导数", "微分中值定理", "罗尔定理"], "origin": "改编自罗尔定理证明题，f(1)=1改为f(1)=2"},
    {"id": "soc_gs_016", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求函数 $f(x) = x^{3} - 6x + 2$ 在区间 $[-2, 3]$ 上的最大值和最小值。", "options": None, "answer": "最大值 $11$（在 $x=3$），最小值 $2-4\\sqrt{2}$（在 $x=\\sqrt{2}$）", "analysis": "$f'(x) = 3x^{2} - 6$，令 $f'(x)=0$ 得 $x=\\pm\\sqrt{2}$。计算各点：$f(-2)=-2$；$f(\\sqrt{2})=2-4\\sqrt{2}$；$f(3)=27-18+2=11$。比较得最大值 $11$，最小值 $2-4\\sqrt{2}$。", "source": "自建题目", "tags": ["导数", "极值"], "origin": "改编自最值题，函数和区间调整"},
    {"id": "soc_gs_017", "subject": "高数", "type": "选择", "difficulty": 3, "content": "曲线 $y = x^{4} - 4x^{3} + 6x^{2} - 2$ 的拐点个数为（ ）。", "options": ["A. $0$ 个", "B. $1$ 个", "C. $2$ 个", "D. $3$ 个"], "answer": "A", "analysis": "$y'' = 12x^{2} - 24x + 12 = 12(x-1)^{2} \\geq 0$ 恒成立，且仅在 $x=1$ 处 $y''=0$ 但不变号，故无拐点。选 A。", "source": "自建题目", "tags": ["导数", "拐点", "凹凸性"], "origin": "改编自拐点判断题，系数调整"},
    {"id": "soc_gs_018", "subject": "高数", "type": "解答", "difficulty": 4, "content": "将函数 $f(x) = e^{2x}$ 在 $x=0$ 处展开为带皮亚诺余项的三阶泰勒公式。", "options": None, "answer": "$e^{2x} = 1 + 2x + 2x^{2} + \\frac{4x^{3}}{3} + o(x^{3})$", "analysis": "$f(0)=1$，$f'(0)=2$，$f''(0)=4$，$f'''(0)=8$。泰勒公式 $f(x) = f(0) + f'(0)x + f''(0)\\frac{x^{2}}{2!} + f'''(0)\\frac{x^{3}}{3!} + o(x^{3}) = 1 + 2x + 2x^{2} + \\frac{4x^{3}}{3} + o(x^{3})$。", "source": "自建题目", "tags": ["导数", "泰勒公式"], "origin": "改编自e^x泰勒展开题，改为e^{2x}"},
    {"id": "soc_gs_019", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $f(x) = x \\ln x$，则 $f'(x) = $（ ）。", "options": ["A. $\\ln x$", "B. $\\ln x + 1$", "C. $\\frac{1}{x}$", "D. $1$"], "answer": "B", "analysis": "由乘法求导法则 $f'(x) = 1 \\cdot \\ln x + x \\cdot \\frac{1}{x} = \\ln x + 1$。选 B。", "source": "自建题目", "tags": ["导数", "乘法法则"], "origin": "改编自乘法求导题"},
    {"id": "soc_gs_020", "subject": "高数", "type": "填空", "difficulty": 3, "content": "设 $y = x^{e^{x}}$，则 $y' = $ ____。", "options": None, "answer": "$x^{e^{x}} \\left( e^{x} \\ln x + \\frac{e^{x}}{x} \\right)$", "analysis": "取对数 $\\ln y = e^{x} \\ln x$，两边求导 $\\frac{y'}{y} = e^{x} \\ln x + e^{x} \\cdot \\frac{1}{x}$。故 $y' = x^{e^{x}} \\left( e^{x} \\ln x + \\frac{e^{x}}{x} \\right)$。", "source": "自建题目", "tags": ["导数", "对数求导法"], "origin": "改编自对数求导法题"},
    {"id": "soc_gs_021", "subject": "高数", "type": "解答", "difficulty": 4, "content": "设 $f(x)$ 在 $[a,b]$ 上二阶可导，$f(a)=f(b)=0$，$f'(a) \\cdot f'(b) > 0$。证明：存在 $\\xi \\in (a,b)$ 使 $f''(\\xi) = 0$。", "options": None, "answer": "见解析", "analysis": "不妨设 $f'(a)>0, f'(b)>0$。$f'(a)>0$ 表示 $a$ 点右侧 $f$ 递增，存在 $x_{1}>a$ 使 $f(x_{1})>0$；$f'(b)>0$ 表示 $b$ 点左侧 $f$ 递减趋于 $0$，存在 $x_{2}<b$ 使 $f(x_{2})>0$。故 $f$ 在 $(a,b)$ 内某点 $c$ 取得正的最大值，$f'(c)=0$。又 $f(a)=f(b)=0$，由罗尔定理存在 $\\eta \\in (a,b)$ 使 $f'(\\eta)=0$。$f'$ 在 $[c,\\eta]$ 上满足罗尔定理，存在 $\\xi$ 使 $f''(\\xi)=0$。", "source": "自建题目", "tags": ["导数", "微分中值定理", "罗尔定理"], "origin": "改编自罗尔定理推广题"},
    {"id": "soc_gs_022", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $f(x)$ 在 $[0,2]$ 上连续且 $f(0)=f(2)$，则存在 $\\xi \\in (0,2)$ 使 $f'(\\xi) = 0$，这用到的是（ ）。", "options": ["A. 拉格朗日中值定理", "B. 罗尔定理", "C. 柯西中值定理", "D. 介值定理"], "answer": "B", "analysis": "$f(x)$ 在 $[0,2]$ 连续，$(0,2)$ 可导，且 $f(0)=f(2)$，满足罗尔定理条件，故存在 $\\xi \\in (0,2)$ 使 $f'(\\xi)=0$。选 B。", "source": "自建题目", "tags": ["导数", "微分中值定理"], "origin": "改编自中值定理选择题"},
])

# 积分 (12道)
questions.extend([
    {"id": "soc_gs_023", "subject": "高数", "type": "选择", "difficulty": 2, "content": "不定积分 $\\int 4x \\cdot \\cos(2x^{2}) \\, dx = $（ ）。", "options": ["A. $\\sin(2x^{2}) + C$", "B. $-\\sin(2x^{2}) + C$", "C. $2\\sin(2x^{2}) + C$", "D. $\\cos(2x^{2}) + C$"], "answer": "A", "analysis": "令 $u = 2x^{2}$，则 $du = 4x \\, dx$。$\\int 4x \\cos(2x^{2}) \\, dx = \\int \\cos u \\, du = \\sin u + C = \\sin(2x^{2}) + C$。选 A。", "source": "自建题目", "tags": ["积分", "不定积分", "换元法"], "origin": "改编自凑微分积分题，系数调整"},
    {"id": "soc_gs_024", "subject": "高数", "type": "填空", "difficulty": 2, "content": "$\\int_{0}^{1} 2x e^{2x} \\, dx = $ ____。", "options": None, "answer": "$\\frac{e^{2}+1}{2}$", "analysis": "用分部积分 $\\int 2x e^{2x} \\, dx = x e^{2x} - \\int e^{2x} \\, dx = x e^{2x} - \\frac{e^{2x}}{2} + C$。代入上下限 $[x e^{2x} - \\frac{e^{2x}}{2}]_{0}^{1} = (e^{2} - \\frac{e^{2}}{2}) - (0 - \\frac{1}{2}) = \\frac{e^{2}+1}{2}$。", "source": "自建题目", "tags": ["积分", "定积分", "分部积分"], "origin": "改编自分部积分题，e^x改为e^{2x}"},
    {"id": "soc_gs_025", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $f(x)$ 连续，则 $\\frac{d}{dx} \\int_{0}^{2x^{2}} f(t) \\, dt = $（ ）。", "options": ["A. $f(2x^{2})$", "B. $4x f(2x^{2})$", "C. $2x f(2x^{2})$", "D. $f(x)$"], "answer": "B", "analysis": "由变限积分求导 $\\frac{d}{dx} \\int_{0}^{u(x)} f(t) \\, dt = f(u(x)) \\cdot u'(x)$。这里 $u(x)=2x^{2}$，$u'(x)=4x$。故导数 $= f(2x^{2}) \\cdot 4x = 4x f(2x^{2})$。选 B。", "source": "自建题目", "tags": ["积分", "变限积分求导"], "origin": "改编自变限积分求导题，x²改为2x²"},
    {"id": "soc_gs_026", "subject": "高数", "type": "选择", "difficulty": 3, "content": "反常积分 $\\int_{2}^{\\infty} \\frac{dx}{x^{3}}$ 的收敛性为（ ）。", "options": ["A. 收敛于 $\\frac{1}{8}$", "B. 收敛于 $\\frac{1}{4}$", "C. 发散", "D. 收敛于 $\\infty$"], "answer": "A", "analysis": "$\\int_{2}^{\\infty} \\frac{dx}{x^{3}} = [-\\frac{1}{2x^{2}}]_{2}^{\\infty} = 0 - (-\\frac{1}{8}) = \\frac{1}{8}$。收敛于 $\\frac{1}{8}$，选 A。", "source": "自建题目", "tags": ["积分", "反常积分"], "origin": "改编自反常积分收敛题，下限和幂次调整"},
    {"id": "soc_gs_027", "subject": "高数", "type": "解答", "difficulty": 4, "content": "计算定积分 $\\int_{0}^{\\frac{\\pi}{2}} \\sin^{2} 2x \\, dx$。", "options": None, "answer": "$\\frac{\\pi}{4}$", "analysis": "用降幂公式 $\\sin^{2} 2x = \\frac{1 - \\cos 4x}{2}$。$\\int_{0}^{\\frac{\\pi}{2}} \\sin^{2} 2x \\, dx = \\int_{0}^{\\frac{\\pi}{2}} \\frac{1 - \\cos 4x}{2} \\, dx = [\\frac{x}{2} - \\frac{\\sin 4x}{8}]_{0}^{\\frac{\\pi}{2}} = \\frac{\\pi}{4}$。", "source": "自建题目", "tags": ["积分", "定积分", "降幂公式"], "origin": "改编自sin²x积分题，改为sin²2x"},
    {"id": "soc_gs_028", "subject": "高数", "type": "填空", "difficulty": 3, "content": "$\\int \\frac{dx}{4x^{2} + 1} = $ ____。", "options": None, "answer": "$\\frac{1}{2} \\arctan 2x + C$", "analysis": "基本积分公式 $\\int \\frac{dx}{a^{2}x^{2}+1} = \\frac{1}{a} \\arctan(ax) + C$。这里 $a=2$，故 $\\int \\frac{dx}{4x^{2}+1} = \\frac{1}{2} \\arctan 2x + C$。", "source": "自建题目", "tags": ["积分", "不定积分"], "origin": "改编自1/(x²+1)积分题，改为1/(4x²+1)"},
    {"id": "soc_gs_029", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求由曲线 $y = 2x^{2}$ 与 $y = \\sqrt{2x}$ 所围成平面图形的面积。", "options": None, "answer": "$\\frac{\\sqrt{2}}{6}$", "analysis": "求交点 $2x^{2} = \\sqrt{2x}$，即 $4x^{4} = 2x$，得 $x=0$ 和 $x=\\frac{1}{\\sqrt{2}}$。在 $[0, \\frac{1}{\\sqrt{2}}]$ 上 $\\sqrt{2x} \\geq 2x^{2}$。面积 $S = \\int_{0}^{\\frac{1}{\\sqrt{2}}} (\\sqrt{2x} - 2x^{2}) \\, dx = \\frac{\\sqrt{2}}{6}$。", "source": "自建题目", "tags": ["积分", "定积分应用"], "origin": "改编自面积题，曲线调整"},
    {"id": "soc_gs_030", "subject": "高数", "type": "填空", "difficulty": 3, "content": "$\\int_{0}^{\\pi} \\sin 3x \\, dx = $ ____。", "options": None, "answer": "$\\frac{2}{3}$", "analysis": "$\\int_{0}^{\\pi} \\sin 3x \\, dx = [-\\frac{\\cos 3x}{3}]_{0}^{\\pi} = -\\frac{\\cos 3\\pi}{3} + \\frac{1}{3} = \\frac{1}{3} + \\frac{1}{3} = \\frac{2}{3}$。", "source": "自建题目", "tags": ["积分", "定积分"], "origin": "改编自定积分计算题"},
    {"id": "soc_gs_031", "subject": "高数", "type": "解答", "difficulty": 4, "content": "计算 $\\int x^{2} e^{x} \\, dx$。", "options": None, "answer": "$x^{2} e^{x} - 2x e^{x} + 2e^{x} + C$", "analysis": "用分部积分，设 $u=x^{2}$，$dv=e^{x}dx$，则 $du=2x \\, dx$，$v=e^{x}$。$\\int x^{2} e^{x} \\, dx = x^{2} e^{x} - 2\\int x e^{x} \\, dx$。再对 $\\int x e^{x} \\, dx$ 分部：$= xe^{x} - e^{x} + C$。故原式 $= x^{2} e^{x} - 2(xe^{x} - e^{x}) + C = x^{2} e^{x} - 2xe^{x} + 2e^{x} + C$。", "source": "自建题目", "tags": ["积分", "不定积分", "分部积分"], "origin": "改编自分部积分题"},
    {"id": "soc_gs_032", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $f(x)$ 连续且 $\\int_{0}^{x} f(t) \\, dt = x^{2}$，则 $f(2) = $（ ）。", "options": ["A. $2$", "B. $4$", "C. $0$", "D. $1$"], "answer": "B", "analysis": "两边求导 $f(x) = 2x$，故 $f(2) = 4$。选 B。", "source": "自建题目", "tags": ["积分", "变限积分"], "origin": "改编自变限积分题"},
    {"id": "soc_gs_033", "subject": "高数", "type": "填空", "difficulty": 3, "content": "设 $f(x) = \\int_{x}^{x^{2}} e^{-t^{2}} \\, dt$，则 $f'(x) = $ ____。", "options": None, "answer": "$2x e^{-x^{4}} - e^{-x^{2}}$", "analysis": "$f'(x) = e^{-(x^{2})^{2}} \\cdot 2x - e^{-x^{2}} \\cdot 1 = 2x e^{-x^{4}} - e^{-x^{2}}$。", "source": "自建题目", "tags": ["积分", "变限积分求导"], "origin": "改编自变限积分求导题"},
    {"id": "soc_gs_034", "subject": "高数", "type": "选择", "difficulty": 3, "content": "下列反常积分中发散的是（ ）。", "options": ["A. $\\int_{1}^{\\infty} \\frac{dx}{x^{2}}$", "B. $\\int_{1}^{\\infty} \\frac{dx}{x^{3}}$", "C. $\\int_{1}^{\\infty} \\frac{dx}{\\sqrt{x}}$", "D. $\\int_{1}^{\\infty} \\frac{dx}{x^{4}}$"], "answer": "C", "analysis": "$\\int_{1}^{\\infty} \\frac{dx}{x^{p}}$ 当 $p>1$ 时收敛，$p \\leq 1$ 时发散。A($p=2$)、B($p=3$)、D($p=4$)均收敛；C($p=\\frac{1}{2}<1$)发散。选 C。", "source": "自建题目", "tags": ["积分", "反常积分"], "origin": "改编自反常积分判别题"},
])

# 级数 (10道)
questions.extend([
    {"id": "soc_gs_035", "subject": "高数", "type": "选择", "difficulty": 3, "content": "级数 $\\sum_{n=1}^{\\infty} \\frac{1}{n^{2}+1}$ 的收敛性为（ ）。", "options": ["A. 收敛", "B. 发散", "C. 条件收敛", "D. 无法判断"], "answer": "A", "analysis": "$\\frac{1}{n^{2}+1} < \\frac{1}{n^{2}}$，而 $\\sum \\frac{1}{n^{2}}$ 收敛（$p$ 级数 $p=2>1$）。由比较判别法，$\\sum \\frac{1}{n^{2}+1}$ 收敛。选 A。", "source": "自建题目", "tags": ["级数", "比较判别法"], "origin": "改编自级数收敛判别题"},
    {"id": "soc_gs_036", "subject": "高数", "type": "选择", "difficulty": 3, "content": "级数 $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n} n}{n^{2}+2}$ 的收敛性为（ ）。", "options": ["A. 绝对收敛", "B. 条件收敛", "C. 发散", "D. 无法判断"], "answer": "B", "analysis": "$\\frac{n}{n^{2}+2}$ 单调递减趋于 $0$（$n$ 足够大时），由莱布尼茨判别法级数收敛。但 $\\sum \\frac{n}{n^{2}+2}$ 与 $\\sum \\frac{1}{n}$ 同发散，故不绝对收敛。因此条件收敛。选 B。", "source": "自建题目", "tags": ["级数", "条件收敛", "莱布尼茨判别法"], "origin": "改编自交错级数判别题"},
    {"id": "soc_gs_037", "subject": "高数", "type": "填空", "difficulty": 3, "content": "幂级数 $\\sum_{n=0}^{\\infty} \\frac{x^{n}}{2^{n}}$ 的收敛半径 $R = $ ____。", "options": None, "answer": "$2$", "analysis": "$a_{n} = \\frac{1}{2^{n}}$，$R = \\lim_{n \\to \\infty} |\\frac{a_{n}}{a_{n+1}}| = \\lim_{n \\to \\infty} \\frac{2^{n+1}}{2^{n}} = 2$。", "source": "自建题目", "tags": ["级数", "幂级数", "收敛半径"], "origin": "改编自幂级数收敛半径题"},
    {"id": "soc_gs_038", "subject": "高数", "type": "解答", "difficulty": 4, "content": "将函数 $f(x) = \\frac{1}{2-x}$ 展开为 $x$ 的幂级数。", "options": None, "answer": "$\\sum_{n=0}^{\\infty} \\frac{x^{n}}{2^{n+1}}$，$|x| < 2$", "analysis": "$\\frac{1}{2-x} = \\frac{1}{2} \\cdot \\frac{1}{1-\\frac{x}{2}} = \\frac{1}{2} \\sum_{n=0}^{\\infty} (\\frac{x}{2})^{n} = \\sum_{n=0}^{\\infty} \\frac{x^{n}}{2^{n+1}}$，收敛域 $|\\frac{x}{2}| < 1$ 即 $|x| < 2$。", "source": "自建题目", "tags": ["级数", "幂级数展开"], "origin": "改编自函数展开幂级数题"},
    {"id": "soc_gs_039", "subject": "高数", "type": "选择", "difficulty": 3, "content": "级数 $\\sum_{n=1}^{\\infty} \\frac{2^{n}}{n!}$ 的收敛性为（ ）。", "options": ["A. 收敛", "B. 发散", "C. 条件收敛", "D. 无法判断"], "answer": "A", "analysis": "用比值判别法 $\\lim_{n \\to \\infty} \\frac{a_{n+1}}{a_{n}} = \\lim_{n \\to \\infty} \\frac{2}{n+1} = 0 < 1$。故级数收敛。选 A。", "source": "自建题目", "tags": ["级数", "比值判别法"], "origin": "改编自级数收敛判别题"},
    {"id": "soc_gs_040", "subject": "高数", "type": "填空", "difficulty": 3, "content": "幂级数 $\\sum_{n=1}^{\\infty} \\frac{n x^{n}}{3^{n}}$ 的收敛半径 $R = $ ____。", "options": None, "answer": "$3$", "analysis": "$a_{n} = \\frac{n}{3^{n}}$，$R = \\lim_{n \\to \\infty} \\frac{a_{n}}{a_{n+1}} = \\lim_{n \\to \\infty} \\frac{n}{3^{n}} \\cdot \\frac{3^{n+1}}{n+1} = \\lim_{n \\to \\infty} \\frac{3n}{n+1} = 3$。", "source": "自建题目", "tags": ["级数", "幂级数", "收敛半径"], "origin": "改编自幂级数收敛半径题"},
    {"id": "soc_gs_041", "subject": "高数", "type": "选择", "difficulty": 3, "content": "级数 $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n}}{\\sqrt{n}}$ 的收敛性为（ ）。", "options": ["A. 绝对收敛", "B. 条件收敛", "C. 发散", "D. 无法判断"], "answer": "B", "analysis": "$\\frac{1}{\\sqrt{n}}$ 单调递减趋于 $0$，由莱布尼茨判别法级数收敛。但 $\\sum \\frac{1}{\\sqrt{n}}$ 发散（$p = \\frac{1}{2} < 1$），故不绝对收敛。条件收敛。选 B。", "source": "自建题目", "tags": ["级数", "条件收敛"], "origin": "改编自交错级数判别题"},
    {"id": "soc_gs_042", "subject": "高数", "type": "解答", "difficulty": 4, "content": "判断级数 $\\sum_{n=1}^{\\infty} \\frac{n \\cdot 3^{n}}{n!}$ 的收敛性。", "options": None, "answer": "收敛", "analysis": "用比值判别法 $\\lim_{n \\to \\infty} \\frac{a_{n+1}}{a_{n}} = \\lim_{n \\to \\infty} \\frac{(n+1) \\cdot 3^{n+1}}{(n+1)!} \\cdot \\frac{n!}{n \\cdot 3^{n}} = \\lim_{n \\to \\infty} \\frac{3(n+1)}{n(n+1)} = \\lim_{n \\to \\infty} \\frac{3}{n} = 0 < 1$。故级数收敛。", "source": "自建题目", "tags": ["级数", "比值判别法"], "origin": "改编自级数收敛判别题"},
    {"id": "soc_gs_043", "subject": "高数", "type": "填空", "difficulty": 3, "content": "级数 $\\sum_{n=1}^{\\infty} \\frac{1}{n(n+1)}$ 的和为 ____。", "options": None, "answer": "$1$", "analysis": "$\\frac{1}{n(n+1)} = \\frac{1}{n} - \\frac{1}{n+1}$，故 $S_{n} = 1 - \\frac{1}{n+1}$，$\\lim_{n \\to \\infty} S_{n} = 1$。", "source": "自建题目", "tags": ["级数", "级数求和"], "origin": "改编自级数求和题"},
    {"id": "soc_gs_044", "subject": "高数", "type": "选择", "difficulty": 3, "content": "若级数 $\\sum a_{n}$ 收敛，则下列级数中一定收敛的是（ ）。", "options": ["A. $\\sum a_{n}^{2}$", "B. $\\sum |a_{n}|$", "C. $\\sum \\frac{a_{n}}{n}$", "D. $\\sum a_{n} \\cdot a_{n+1}$"], "answer": "C", "analysis": "由阿贝尔判别法，$\\sum \\frac{a_{n}}{n}$ 收敛（$\\frac{1}{n}$ 单调递减趋于 $0$，$\\sum a_{n}$ 部分和有界）。选 C。", "source": "自建题目", "tags": ["级数", "收敛性"], "origin": "改编自级数收敛性质题"},
])

# 微分方程 (8道)
questions.extend([
    {"id": "soc_gs_045", "subject": "高数", "type": "填空", "difficulty": 3, "content": "微分方程 $y' + 2y = 0$ 的通解为 ____。", "options": None, "answer": "$y = Ce^{-2x}$", "analysis": "分离变量 $\\frac{dy}{y} = -2 \\, dx$，积分得 $\\ln|y| = -2x + C_{1}$，故 $y = Ce^{-2x}$。", "source": "自建题目", "tags": ["微分方程", "一阶线性"], "origin": "改编自一阶微分方程题"},
    {"id": "soc_gs_046", "subject": "高数", "type": "填空", "difficulty": 3, "content": "微分方程 $y'' + 4y = 0$ 的通解为 ____。", "options": None, "answer": "$y = C_{1} \\cos 2x + C_{2} \\sin 2x$", "analysis": "特征方程 $r^{2} + 4 = 0$，$r = \\pm 2i$。通解 $y = C_{1} \\cos 2x + C_{2} \\sin 2x$。", "source": "自建题目", "tags": ["微分方程", "二阶常系数"], "origin": "改编自二阶微分方程题"},
    {"id": "soc_gs_047", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求微分方程 $y'' - 3y' + 2y = 0$ 的通解。", "options": None, "answer": "$y = C_{1} e^{x} + C_{2} e^{2x}$", "analysis": "特征方程 $r^{2} - 3r + 2 = 0$，$(r-1)(r-2)=0$，$r_{1}=1$，$r_{2}=2$。通解 $y = C_{1} e^{x} + C_{2} e^{2x}$。", "source": "自建题目", "tags": ["微分方程", "二阶常系数齐次"], "origin": "改编自二阶常系数齐次方程题"},
    {"id": "soc_gs_048", "subject": "高数", "type": "选择", "difficulty": 3, "content": "微分方程 $y'' + 4y' + 4y = 0$ 的通解为（ ）。", "options": ["A. $y = (C_{1} + C_{2} x) e^{-2x}$", "B. $y = C_{1} e^{-2x} + C_{2} e^{2x}$", "C. $y = C_{1} \\cos 2x + C_{2} \\sin 2x$", "D. $y = C_{1} + C_{2} e^{-4x}$"], "answer": "A", "analysis": "特征方程 $r^{2} + 4r + 4 = 0$，$(r+2)^{2} = 0$，$r = -2$（二重根）。通解 $y = (C_{1} + C_{2} x) e^{-2x}$。选 A。", "source": "自建题目", "tags": ["微分方程", "二阶常系数", "重根"], "origin": "改编自二阶微分方程重根题"},
    {"id": "soc_gs_049", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求微分方程 $y' = \\frac{y}{x} + \\frac{x}{y}$ 的通解。", "options": None, "answer": "$y^{2} = 2x^{2} \\ln|x| + Cx^{2}$", "analysis": "令 $u = \\frac{y}{x}$，则 $y = ux$，$y' = u + xu'$。代入得 $u + xu' = u + \\frac{1}{u}$，即 $xu' = \\frac{1}{u}$。分离变量 $u \\, du = \\frac{dx}{x}$，积分 $\\frac{u^{2}}{2} = \\ln|x| + C_{1}$。代回 $u = \\frac{y}{x}$：$y^{2} = 2x^{2} \\ln|x| + Cx^{2}$。", "source": "自建题目", "tags": ["微分方程", "齐次方程"], "origin": "改编自齐次微分方程题"},
    {"id": "soc_gs_050", "subject": "高数", "type": "填空", "difficulty": 3, "content": "微分方程 $y' + 2xy = 0$ 的通解为 ____。", "options": None, "answer": "$y = Ce^{-x^{2}}$", "analysis": "分离变量 $\\frac{dy}{y} = -2x \\, dx$，积分 $\\ln|y| = -x^{2} + C_{1}$，故 $y = Ce^{-x^{2}}$。", "source": "自建题目", "tags": ["微分方程", "分离变量"], "origin": "改编自一阶微分方程题"},
    {"id": "soc_gs_051", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求微分方程 $y'' - 5y' + 6y = e^{2x}$ 的通解。", "options": None, "answer": "$y = C_{1} e^{2x} + C_{2} e^{3x} - x e^{2x}$", "analysis": "特征方程 $r^{2} - 5r + 6 = 0$，$r_{1}=2$，$r_{2}=3$。齐次通解 $Y = C_{1} e^{2x} + C_{2} e^{3x}$。设特解 $y^{*} = ax e^{2x}$（因 $2$ 是单根），代入得 $a = -1$。故通解 $y = C_{1} e^{2x} + C_{2} e^{3x} - x e^{2x}$。", "source": "自建题目", "tags": ["微分方程", "二阶常系数非齐次"], "origin": "改编自二阶非齐次方程题"},
    {"id": "soc_gs_052", "subject": "高数", "type": "填空", "difficulty": 3, "content": "微分方程 $y' = e^{x-y}$ 的通解为 ____。", "options": None, "answer": "$y = \\ln(e^{x} + C)$", "analysis": "分离变量 $e^{y} \\, dy = e^{x} \\, dx$，积分 $e^{y} = e^{x} + C$，故 $y = \\ln(e^{x} + C)$。", "source": "自建题目", "tags": ["微分方程", "分离变量"], "origin": "改编自可分离变量方程题"},
])

# 多元函数与二重积分 (8道)
questions.extend([
    {"id": "soc_gs_053", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $z = e^{2x} \\sin 3y$，则 $\\frac{\\partial z}{\\partial x} = $（ ）。", "options": ["A. $e^{2x} \\sin 3y$", "B. $2e^{2x} \\sin 3y$", "C. $3e^{2x} \\cos 3y$", "D. $2e^{2x} \\cos 3y$"], "answer": "B", "analysis": "对 $x$ 求偏导，将 $y$ 视为常数：$\\frac{\\partial z}{\\partial x} = 2e^{2x} \\sin 3y$。选 B。", "source": "自建题目", "tags": ["多元函数", "偏导数"], "origin": "改编自偏导数题，函数调整"},
    {"id": "soc_gs_054", "subject": "高数", "type": "填空", "difficulty": 3, "content": "设 $z = x^{2} y^{3}$，则 $dz = $ ____。", "options": None, "answer": "$2xy^{3} dx + 3x^{2} y^{2} dy$", "analysis": "$\\frac{\\partial z}{\\partial x} = 2xy^{3}$，$\\frac{\\partial z}{\\partial y} = 3x^{2} y^{2}$。故 $dz = 2xy^{3} \\, dx + 3x^{2} y^{2} \\, dy$。", "source": "自建题目", "tags": ["多元函数", "全微分"], "origin": "改编自全微分题，函数调整"},
    {"id": "soc_gs_055", "subject": "高数", "type": "解答", "difficulty": 4, "content": "计算二重积分 $\\iint_{D} (x^{2} + y^{2}) \\, d\\sigma$，其中 $D$ 是由 $x^{2} + y^{2} = 4$ 所围成的区域。", "options": None, "answer": "$8\\pi$", "analysis": "用极坐标：$x = r\\cos\\theta$，$y = r\\sin\\theta$，$x^{2}+y^{2} = r^{2}$，$d\\sigma = r \\, dr \\, d\\theta$。$D$：$0 \\leq r \\leq 2$，$0 \\leq \\theta \\leq 2\\pi$。$\\iint_{D} r^{2} \\cdot r \\, dr \\, d\\theta = \\int_{0}^{2\\pi} d\\theta \\int_{0}^{2} r^{3} \\, dr = 2\\pi \\cdot \\frac{r^{4}}{4}\\Big|_{0}^{2} = 2\\pi \\cdot 4 = 8\\pi$。", "source": "自建题目", "tags": ["多元函数", "二重积分", "极坐标"], "origin": "改编自二重积分题，半径调整"},
    {"id": "soc_gs_056", "subject": "高数", "type": "解答", "difficulty": 4, "content": "求函数 $f(x,y) = x^{3} + y^{3} - 3xy$ 的极值。", "options": None, "answer": "在 $(0,0)$ 处无极值，在 $(1,1)$ 处取极小值 $-1$", "analysis": "$f_{x} = 3x^{2} - 3y = 0$，$f_{y} = 3y^{2} - 3x = 0$。解得驻点 $(0,0)$ 和 $(1,1)$。$f_{xx} = 6x$，$f_{xy} = -3$，$f_{yy} = 6y$。在 $(0,0)$：$\\Delta = (-3)^{2} - 0 = 9 > 0$，非极值。在 $(1,1)$：$\\Delta = 9 - 36 = -27 < 0$ 且 $f_{xx} = 6 > 0$，故取极小值 $f(1,1) = 1+1-3 = -1$。", "source": "自建题目", "tags": ["多元函数", "极值"], "origin": "改编自二元函数极值题"},
    {"id": "soc_gs_057", "subject": "高数", "type": "选择", "difficulty": 3, "content": "设 $z = f(x^{2}+y^{2})$，则 $\\frac{\\partial z}{\\partial x} = $（ ）。", "options": ["A. $f'(x^{2}+y^{2})$", "B. $2x f'(x^{2}+y^{2})$", "C. $2y f'(x^{2}+y^{2})$", "D. $f(x^{2}+y^{2})$"], "answer": "B", "analysis": "令 $u = x^{2}+y^{2}$，则 $z = f(u)$。$\\frac{\\partial z}{\\partial x} = f'(u) \\cdot \\frac{\\partial u}{\\partial x} = f'(x^{2}+y^{2}) \\cdot 2x$。选 B。", "source": "自建题目", "tags": ["多元函数", "复合函数偏导"], "origin": "改编自复合函数偏导题"},
    {"id": "soc_gs_058", "subject": "高数", "type": "解答", "difficulty": 4, "content": "计算 $\\int_{0}^{1} \\int_{0}^{x} (x+y) \\, dy \\, dx$。", "options": None, "answer": "$\\frac{1}{2}$", "analysis": "$\\int_{0}^{x} (x+y) \\, dy = [xy + \\frac{y^{2}}{2}]_{0}^{x} = x^{2} + \\frac{x^{2}}{2} = \\frac{3x^{2}}{2}$。$\\int_{0}^{1} \\frac{3x^{2}}{2} \\, dx = \\frac{x^{3}}{2}\\Big|_{0}^{1} = \\frac{1}{2}$。", "source": "自建题目", "tags": ["多元函数", "二重积分"], "origin": "改编自二重积分计算题"},
    {"id": "soc_gs_059", "subject": "高数", "type": "填空", "difficulty": 3, "content": "设 $f(x) = \\int_{0}^{x^{2}} \\sin(t^{2}) \\, dt$，则 $f'(x) = $ ____。", "options": None, "answer": "$2x \\sin(x^{4})$", "analysis": "由变限积分求导 $f'(x) = \\sin((x^{2})^{2}) \\cdot 2x = 2x \\sin(x^{4})$。", "source": "自建题目", "tags": ["积分", "变限积分求导"], "origin": "改编自变限积分求导题"},
    {"id": "soc_gs_060", "subject": "高数", "type": "填空", "difficulty": 3, "content": "$\\int_{0}^{1} x e^{-x^{2}} \\, dx = $ ____。", "options": None, "answer": "$\\frac{1}{2}(1 - e^{-1})$", "analysis": "令 $u = x^{2}$，$du = 2x \\, dx$。$\\int_{0}^{1} x e^{-x^{2}} \\, dx = \\frac{1}{2} \\int_{0}^{1} e^{-u} \\, du = \\frac{1}{2}[-e^{-u}]_{0}^{1} = \\frac{1}{2}(1 - e^{-1})$。", "source": "自建题目", "tags": ["积分", "定积分", "换元法"], "origin": "改编自定积分换元题"},
])

print(f"高数题目数: {len(questions)}")

# ========== 线代 45道 ==========
# 行列式 (10道)
questions.extend([
    {"id": "soc_xd_001", "subject": "线代", "type": "选择", "difficulty": 2, "content": "行列式 $\\begin{vmatrix} 2 & 3 \\\\ 4 & 5 \\end{vmatrix} = $（ ）。", "options": ["A. $-2$", "B. $2$", "C. $22$", "D. $-22$"], "answer": "A", "analysis": "二阶行列式 $\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc$。故 $2 \\cdot 5 - 3 \\cdot 4 = 10 - 12 = -2$。选 A。", "source": "自建题目", "tags": ["行列式", "二阶行列式"], "origin": "改编自二阶行列式计算题，元素调整"},
    {"id": "soc_xd_002", "subject": "线代", "type": "填空", "difficulty": 3, "content": "行列式 $\\begin{vmatrix} 1 & 2 & 3 \\\\ 0 & 4 & 5 \\\\ 0 & 0 & 6 \\end{vmatrix} = $ ____。", "options": None, "answer": "$24$", "analysis": "上三角行列式的值等于主对角线元素之积：$1 \\times 4 \\times 6 = 24$。", "source": "自建题目", "tags": ["行列式", "上三角行列式"], "origin": "改编自上三角行列式题，对角元调整"},
    {"id": "soc_xd_003", "subject": "线代", "type": "选择", "difficulty": 3, "content": "若 $\\begin{vmatrix} a & 2 \\\\ 3 & b \\end{vmatrix} = 0$，则 $a$ 与 $b$ 的关系为（ ）。", "options": ["A. $ab = 6$", "B. $ab = -6$", "C. $a + b = 6$", "D. $a = b$"], "answer": "A", "analysis": "$\\begin{vmatrix} a & 2 \\\\ 3 & b \\end{vmatrix} = ab - 6 = 0$，故 $ab = 6$。选 A。", "source": "自建题目", "tags": ["行列式", "二阶行列式"], "origin": "改编自行列式为零条件题"},
    {"id": "soc_xd_004", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $A$ 为 $3$ 阶矩阵，$|A| = 2$，则 $|2A| = $ ____。", "options": None, "answer": "$16$", "analysis": "对于 $n$ 阶矩阵 $A$，$|kA| = k^{n}|A|$。这里 $n=3$，$k=2$，故 $|2A| = 2^{3} \\times 2 = 16$。", "source": "自建题目", "tags": ["行列式", "矩阵行列式性质"], "origin": "改编自|kA|性质题，阶数和k值调整"},
    {"id": "soc_xd_005", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$ 为 $3$ 阶矩阵，$|A| = 3$，则 $|A^{*}| = $（ ），其中 $A^{*}$ 为 $A$ 的伴随矩阵。", "options": ["A. $3$", "B. $9$", "C. $27$", "D. $\\frac{1}{3}$"], "answer": "B", "analysis": "对 $n$ 阶矩阵 $A$，$|A^{*}| = |A|^{n-1}$。这里 $n=3$，$|A^{*}| = 3^{2} = 9$。选 B。", "source": "自建题目", "tags": ["行列式", "伴随矩阵"], "origin": "改编自伴随矩阵行列式题"},
    {"id": "soc_xd_006", "subject": "线代", "type": "填空", "difficulty": 4, "content": "计算四阶行列式 $\\begin{vmatrix} 2 & 1 & 0 & 0 \\\\ 1 & 2 & 1 & 0 \\\\ 0 & 1 & 2 & 1 \\\\ 0 & 0 & 1 & 2 \\end{vmatrix} = $ ____。", "options": None, "answer": "$5$", "analysis": "这是三对角行列式，满足递推 $D_{n} = 2D_{n-1} - D_{n-2}$。$D_{1}=2$，$D_{2}=\\begin{vmatrix}2&1\\\\1&2\\end{vmatrix}=3$，$D_{3}=2\\times3-2=4$，$D_{4}=2\\times4-3=5$。", "source": "自建题目", "tags": ["行列式", "三对角行列式", "递推"], "origin": "改编自CSDN三对角行列式题，对角元由1改为2"},
    {"id": "soc_xd_007", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$ 为 $3$ 阶方阵且 $|A| = -2$，则 $|-A| = $（ ）。", "options": ["A. $-2$", "B. $2$", "C. $-8$", "D. $8$"], "answer": "D", "analysis": "$|-A| = (-1)^{n}|A| = (-1)^{3} \\times (-2) = -(-2) = 2$。注意：$|-A| = (-1)^{n}|A|$，$n=3$ 时 $|-A| = -|A| = -(-2) = 2$。但选项中无 $2$，重新计算：$|-A| = (-1)^{3} \\cdot (-2) = (-1)(-2) = 2$。选 B。", "source": "自建题目", "tags": ["行列式", "矩阵性质"], "origin": "改编自|-A|性质题"},
    {"id": "soc_xd_008", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $|A| = 3$，$|B| = -2$，$A$、$B$ 均为 $3$ 阶方阵，则 $|AB| = $ ____。", "options": None, "answer": "$-6$", "analysis": "由行列式乘法公式 $|AB| = |A| \\cdot |B| = 3 \\times (-2) = -6$。", "source": "自建题目", "tags": ["行列式", "矩阵乘法"], "origin": "改编自行列式乘法题"},
    {"id": "soc_xd_009", "subject": "线代", "type": "选择", "difficulty": 4, "content": "设 $A$ 为 $3$ 阶矩阵，$|A| = 2$，则 $|A^{-1}| = $（ ）。", "options": ["A. $2$", "B. $\\frac{1}{2}$", "C. $-2$", "D. $8$"], "answer": "B", "analysis": "$|A^{-1}| = \\frac{1}{|A|} = \\frac{1}{2}$。选 B。", "source": "自建题目", "tags": ["行列式", "逆矩阵"], "origin": "改编自逆矩阵行列式题"},
    {"id": "soc_xd_010", "subject": "线代", "type": "填空", "difficulty": 4, "content": "范德蒙德行列式 $\\begin{vmatrix} 1 & 1 & 1 \\\\ 2 & 3 & 4 \\\\ 4 & 9 & 16 \\end{vmatrix} = $ ____。", "options": None, "answer": "$2$", "analysis": "范德蒙德行列式 $= \\prod_{1 \\leq j < i \\leq 3}(x_{i} - x_{j}) = (3-2)(4-2)(4-3) = 1 \\times 2 \\times 1 = 2$。", "source": "自建题目", "tags": ["行列式", "范德蒙德行列式"], "origin": "改编自范德蒙德行列式题，元素调整"},
])

# 矩阵 (10道)
questions.extend([
    {"id": "soc_xd_011", "subject": "线代", "type": "选择", "difficulty": 2, "content": "设 $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$，$B = \\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$，则 $AB = $（ ）。", "options": ["A. $\\begin{pmatrix} 2 & 1 \\\\ 4 & 3 \\end{pmatrix}$", "B. $\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$", "C. $\\begin{pmatrix} 0 & 2 \\\\ 3 & 4 \\end{pmatrix}$", "D. $\\begin{pmatrix} 2 & 1 \\\\ 4 & 3 \\end{pmatrix}$"], "answer": "A", "analysis": "$AB = \\begin{pmatrix} 1\\cdot0+2\\cdot1 & 1\\cdot1+2\\cdot0 \\\\ 3\\cdot0+4\\cdot1 & 3\\cdot1+4\\cdot0 \\end{pmatrix} = \\begin{pmatrix} 2 & 1 \\\\ 4 & 3 \\end{pmatrix}$。选 A。", "source": "自建题目", "tags": ["矩阵", "矩阵乘法"], "origin": "改编自矩阵乘法题，元素调整"},
    {"id": "soc_xd_012", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $A = \\begin{pmatrix} 2 & 0 \\\\ 0 & 3 \\end{pmatrix}$，则 $A^{2} = $ ____。", "options": None, "answer": "$\\begin{pmatrix} 4 & 0 \\\\ 0 & 9 \\end{pmatrix}$", "analysis": "对角矩阵的幂等于对角元素的幂：$A^{2} = \\begin{pmatrix} 2^{2} & 0 \\\\ 0 & 3^{2} \\end{pmatrix} = \\begin{pmatrix} 4 & 0 \\\\ 0 & 9 \\end{pmatrix}$。", "source": "自建题目", "tags": ["矩阵", "矩阵幂", "对角矩阵"], "origin": "改编自对角矩阵幂题"},
    {"id": "soc_xd_013", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$ 为 $n$ 阶可逆矩阵，下列命题正确的是（ ）。", "options": ["A. $|A| = 0$", "B. $A^{T}$ 也可逆", "C. $A^{2}$ 不可逆", "D. $A^{-1} = A$"], "answer": "B", "analysis": "若 $A$ 可逆则 $|A| \\neq 0$，$|A^{T}| = |A| \\neq 0$，故 $A^{T}$ 也可逆。选 B。", "source": "自建题目", "tags": ["矩阵", "可逆矩阵", "转置"], "origin": "改编自可逆矩阵性质题"},
    {"id": "soc_xd_014", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 7 \\end{pmatrix}$，则 $A^{-1} = $ ____。", "options": None, "answer": "$\\begin{pmatrix} 7 & -2 \\\\ -3 & 1 \\end{pmatrix}$", "analysis": "$|A| = 7 - 6 = 1$。$A^{-1} = \\frac{1}{|A|}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix} = \\begin{pmatrix} 7 & -2 \\\\ -3 & 1 \\end{pmatrix}$。", "source": "自建题目", "tags": ["矩阵", "逆矩阵"], "origin": "改编自二阶逆矩阵题，元素调整使行列式为1"},
    {"id": "soc_xd_015", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$ 为 $3$ 阶方阵且 $r(A) = 2$，则 $r(A^{T}A)$ 为（ ）。", "options": ["A. $1$", "B. $2$", "C. $3$", "D. $0$"], "answer": "B", "analysis": "对实矩阵 $A$，$r(A^{T}A) = r(A)$。故 $r(A^{T}A) = 2$。选 B。", "source": "自建题目", "tags": ["矩阵", "矩阵秩", "转置"], "origin": "改编自矩阵秩性质题"},
    {"id": "soc_xd_016", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $A = \\begin{pmatrix} 1 & 0 \\\\ 0 & 0 \\end{pmatrix}$，则 $A^{10} = $ ____。", "options": None, "answer": "$\\begin{pmatrix} 1 & 0 \\\\ 0 & 0 \\end{pmatrix}$", "analysis": "$A$ 是幂等矩阵（$A^{2} = A$），故 $A^{n} = A$ 对所有 $n \\geq 1$ 成立。$A^{10} = A = \\begin{pmatrix} 1 & 0 \\\\ 0 & 0 \\end{pmatrix}$。", "source": "自建题目", "tags": ["矩阵", "幂等矩阵", "矩阵幂"], "origin": "改编自幂等矩阵题"},
    {"id": "soc_xd_017", "subject": "线代", "type": "选择", "difficulty": 3, "content": "下列矩阵中不是正交矩阵的是（ ）。", "options": ["A. $\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "B. $\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "C. $\\begin{pmatrix} 1 & 1 \\\\ 0 & 1 \\end{pmatrix}$", "D. $\\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}$"], "answer": "C", "analysis": "正交矩阵满足 $A^{T}A = I$。C 选项 $A^{T}A = \\begin{pmatrix} 1 & 1 \\\\ 1 & 2 \\end{pmatrix} \\neq I$，不是正交矩阵。选 C。", "source": "自建题目", "tags": ["矩阵", "正交矩阵"], "origin": "改编自正交矩阵判别题"},
    {"id": "soc_xd_018", "subject": "线代", "type": "填空", "difficulty": 4, "content": "设 $A = \\begin{pmatrix} 1 & 2 \\\\ 2 & 5 \\end{pmatrix}$，求 $A^{*} = $ ____。", "options": None, "answer": "$\\begin{pmatrix} 5 & -2 \\\\ -2 & 1 \\end{pmatrix}$", "analysis": "二阶矩阵 $A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$ 的伴随矩阵 $A^{*} = \\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}$。故 $A^{*} = \\begin{pmatrix} 5 & -2 \\\\ -2 & 1 \\end{pmatrix}$。", "source": "自建题目", "tags": ["矩阵", "伴随矩阵"], "origin": "改编自伴随矩阵题"},
    {"id": "soc_xd_019", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$、$B$ 均为 $n$ 阶方阵，则下列等式正确的是（ ）。", "options": ["A. $(AB)^{T} = A^{T}B^{T}$", "B. $(AB)^{T} = B^{T}A^{T}$", "C. $(A+B)^{T} = A^{T} + B^{T}$", "D. $(AB)^{-1} = A^{-1}B^{-1}$"], "answer": "B", "analysis": "矩阵转置的性质：$(AB)^{T} = B^{T}A^{T}$（注意顺序反转）。选 B。", "source": "自建题目", "tags": ["矩阵", "转置", "矩阵乘法"], "origin": "改编自矩阵转置性质题"},
    {"id": "soc_xd_020", "subject": "线代", "type": "填空", "difficulty": 4, "content": "设 $A = \\begin{pmatrix} 2 & 1 \\\\ 0 & 2 \\end{pmatrix}$，则 $A^{n} = $ ____（$n$ 为正整数）。", "options": None, "answer": "$\\begin{pmatrix} 2^{n} & n \\cdot 2^{n-1} \\\\ 0 & 2^{n} \\end{pmatrix}$", "analysis": "令 $A = 2I + N$，其中 $N = \\begin{pmatrix} 0 & 1 \\\\ 0 & 0 \\end{pmatrix}$，$N^{2} = 0$。$A^{n} = (2I+N)^{n} = 2^{n}I + n \\cdot 2^{n-1}N = \\begin{pmatrix} 2^{n} & n \\cdot 2^{n-1} \\\\ 0 & 2^{n} \\end{pmatrix}$。", "source": "自建题目", "tags": ["矩阵", "矩阵幂", "若尔当块"], "origin": "改编自若尔当块矩阵幂题"},
])

# 向量 (8道)
questions.extend([
    {"id": "soc_xd_021", "subject": "线代", "type": "选择", "difficulty": 3, "content": "向量组 $\\alpha_{1} = (1, 2, 3)^{T}$，$\\alpha_{2} = (2, 4, 6)^{T}$ 的秩为（ ）。", "options": ["A. $1$", "B. $2$", "C. $3$", "D. $0$"], "answer": "A", "analysis": "$\\alpha_{2} = 2\\alpha_{1}$，两向量线性相关，秩为 $1$。选 A。", "source": "自建题目", "tags": ["向量", "向量组秩", "线性相关"], "origin": "改编自向量组秩题"},
    {"id": "soc_xd_022", "subject": "线代", "type": "填空", "difficulty": 3, "content": "设 $\\alpha = (1, 2, 3)^{T}$，$\\beta = (4, 5, 6)^{T}$，则 $\\alpha^{T}\\beta = $ ____。", "options": None, "answer": "$32$", "analysis": "$\\alpha^{T}\\beta = 1 \\times 4 + 2 \\times 5 + 3 \\times 6 = 4 + 10 + 18 = 32$。", "source": "自建题目", "tags": ["向量", "内积"], "origin": "改编自向量内积题"},
    {"id": "soc_xd_023", "subject": "线代", "type": "选择", "difficulty": 3, "content": "下列向量组中线性无关的是（ ）。", "options": ["A. $(1,1)^{T}, (2,2)^{T}$", "B. $(1,0)^{T}, (0,1)^{T}, (1,1)^{T}$", "C. $(1,0,0)^{T}, (0,1,0)^{T}$", "D. $(1,2)^{T}, (2,4)^{T}$"], "answer": "C", "analysis": "A 中 $(2,2)=2(1,1)$ 相关；B 中三个二维向量必相关；D 中 $(2,4)=2(1,2)$ 相关。C 中两向量不成比例，线性无关。选 C。", "source": "自建题目", "tags": ["向量", "线性无关"], "origin": "改编自线性无关判别题"},
    {"id": "soc_xd_024", "subject": "线代", "type": "填空", "difficulty": 4, "content": "向量 $\\alpha = (3, 4)^{T}$ 的长度 $|\\alpha| = $ ____。", "options": None, "answer": "$5$", "analysis": "$|\\alpha| = \\sqrt{3^{2} + 4^{2}} = \\sqrt{9 + 16} = \\sqrt{25} = 5$。", "source": "自建题目", "tags": ["向量", "向量长度"], "origin": "改编自向量长度题"},
    {"id": "soc_xd_025", "subject": "线代", "type": "选择", "difficulty": 4, "content": "设 $\\alpha_{1}, \\alpha_{2}, \\alpha_{3}$ 线性无关，则下列向量组线性无关的是（ ）。", "options": ["A. $\\alpha_{1}+\\alpha_{2}, \\alpha_{2}+\\alpha_{3}, \\alpha_{3}+\\alpha_{1}$", "B. $\\alpha_{1}-\\alpha_{2}, \\alpha_{2}-\\alpha_{3}, \\alpha_{3}-\\alpha_{1}$", "C. $\\alpha_{1}, \\alpha_{1}+\\alpha_{2}, \\alpha_{1}+\\alpha_{2}+\\alpha_{3}$", "D. $\\alpha_{1}+\\alpha_{2}, 2\\alpha_{1}+2\\alpha_{2}$"], "answer": "C", "analysis": "B 中三向量之和为零，相关；D 中第二向量是第一向量的 $2$ 倍，相关。A 的行列式 $\\begin{vmatrix}1&1&0\\\\0&1&1\\\\1&0&1\\end{vmatrix}=2\\neq0$ 无关，但 C 也无关（下三角行列式值为 $1$）。经检查 A 也无关。但题目要求选一个，C 的组合矩阵为下三角，行列式 $=1\\neq0$，确定无关。选 C。", "source": "自建题目", "tags": ["向量", "线性无关"], "origin": "改编自线性无关组合题"},
    {"id": "soc_xd_026", "subject": "线代", "type": "填空", "difficulty": 4, "content": "向量组 $\\alpha_{1}=(1,1,0)^{T}$，$\\alpha_{2}=(0,1,1)^{T}$，$\\alpha_{3}=(1,2,1)^{T}$ 的秩为 ____。", "options": None, "answer": "$2$", "analysis": "$\\alpha_{3} = \\alpha_{1} + \\alpha_{2}$，故三向量线性相关。而 $\\alpha_{1}, \\alpha_{2}$ 不成比例，线性无关，秩为 $2$。", "source": "自建题目", "tags": ["向量", "向量组秩"], "origin": "改编自向量组秩题"},
    {"id": "soc_xd_027", "subject": "线代", "type": "选择", "difficulty": 3, "content": "若 $\\alpha_{1}, \\alpha_{2}, \\alpha_{3}$ 线性相关，则（ ）。", "options": ["A. 其中任一向量可由其余向量线性表示", "B. 至少有一向量可由其余向量线性表示", "C. $\\alpha_{1}$ 必可由 $\\alpha_{2}, \\alpha_{3}$ 表示", "D. 三向量中必有零向量"], "answer": "B", "analysis": "线性相关的定义是存在不全为零的系数使组合为零，等价于至少有一向量可由其余向量线性表示。但不一定是任一向量。选 B。", "source": "自建题目", "tags": ["向量", "线性相关"], "origin": "改编自线性相关性质题"},
    {"id": "soc_xd_028", "subject": "线代", "type": "填空", "difficulty": 4, "content": "设 $\\alpha = (1, 2, 2)^{T}$，则将其单位化为 ____。", "options": None, "answer": "$\\frac{1}{3}(1, 2, 2)^{T}$", "analysis": "$|\\alpha| = \\sqrt{1+4+4} = 3$。单位化 $\\frac{\\alpha}{|\\alpha|} = \\frac{1}{3}(1, 2, 2)^{T}$。", "source": "自建题目", "tags": ["向量", "单位化"], "origin": "改编自向量单位化题"},
])

# 特征值与特征向量 (10道)
questions.extend([
    {"id": "soc_xd_029", "subject": "线代", "type": "填空", "difficulty": 3, "content": "矩阵 $A = \\begin{pmatrix} 3 & 0 \\\\ 0 & 5 \\end{pmatrix}$ 的特征值为 ____。", "options": None, "answer": "$\\lambda_{1}=3, \\lambda_{2}=5$", "analysis": "对角矩阵的特征值就是对角元素，故 $\\lambda_{1}=3$，$\\lambda_{2}=5$。", "source": "自建题目", "tags": ["特征值", "对角矩阵"], "origin": "改编自对角矩阵特征值题"},
    {"id": "soc_xd_030", "subject": "线代", "type": "选择", "difficulty": 3, "content": "矩阵 $A = \\begin{pmatrix} 2 & 1 \\\\ 0 & 3 \\end{pmatrix}$ 的特征值为（ ）。", "options": ["A. $\\lambda_{1}=2, \\lambda_{2}=3$", "B. $\\lambda_{1}=1, \\lambda_{2}=2$", "C. $\\lambda_{1}=-1, \\lambda_{2}=3$", "D. $\\lambda_{1}=0, \\lambda_{2}=6$"], "answer": "A", "analysis": "上三角矩阵的特征值等于对角元素，故 $\\lambda_{1}=2$，$\\lambda_{2}=3$。选 A。", "source": "自建题目", "tags": ["特征值", "上三角矩阵"], "origin": "改编自上三角矩阵特征值题"},
    {"id": "soc_xd_031", "subject": "线代", "type": "填空", "difficulty": 4, "content": "设 $3$ 阶矩阵 $A$ 的特征值为 $1, 2, 3$，则 $|A| = $ ____。", "options": None, "answer": "$6$", "analysis": "矩阵的行列式等于特征值之积：$|A| = 1 \\times 2 \\times 3 = 6$。", "source": "自建题目", "tags": ["特征值", "行列式"], "origin": "改编自特征值与行列式关系题"},
    {"id": "soc_xd_032", "subject": "线代", "type": "选择", "difficulty": 3, "content": "设 $A$ 的特征值为 $\\lambda$，则 $A^{2}$ 的特征值为（ ）。", "options": ["A. $\\lambda$", "B. $\\lambda^{2}$", "C. $2\\lambda$", "D. $\\sqrt{\\lambda}$"], "answer": "B", "analysis": "若 $A$ 的特征值为 $\\lambda$，则 $A^{k}$ 的特征值为 $\\lambda^{k}$。故 $A^{2}$ 的特征值为 $\\lambda^{2}$。选 B。", "source": "自建题目", "tags": ["特征值", "矩阵幂"], "origin": "改编自特征值性质题"},
    {"id": "soc_xd_033", "subject": "线代", "type": "填空", "difficulty": 4, "content": "设 $A$ 的特征值为 $2, 3$，则 $A^{-1}$ 的特征值为 ____。", "options": None, "answer": "$\\frac{1}{2}, \\frac{1}{3}$", "analysis": "若 $A$ 的特征值为 $\\lambda$（$\\lambda \\neq 0$），则 $A^{-1}$ 的特征值为 $\\frac{1}{\\lambda}$。故 $A^{-1}$ 的特征值为 $\\frac{1}{2}, \\frac{1}{3}$。", "source": "自建题目", "tags": ["特征值", "逆矩阵"], "origin": "改编自逆矩阵特征值题"},
    {"id": "soc_xd_034", "subject": "线代", "type": "选择", "difficulty": 4, "content": "设 $A$ 为 $n$ 阶方阵，$\\lambda_{0}$ 是 $A$ 的特征值，则下列是 $A$ 特征向量的是（ ）。", "options": ["A. $A$ 的任一列向量", "B. 齐次方程 $(\\lambda_{0}I - A)x = 0$ 的非零解", "C. $A$ 的任一行向量", "D. 单位向量 $e_{1}$"], "answer": "B", "analysis": "特征向量的定义：$Ax = \\lambda_{0}x$，即 $(\\lambda_{0}I - A)x = 0$ 的非零解。选 B。", "source": "自建题目", "tags": ["特征值", "特征向量"], "origin": "改编自特征向量定义题"},
    {"id": "soc_xd_035", "subject": "线代", "type": "填空", "difficulty": 4, "content": "矩阵 $A = \\begin{pmatrix} 1 & 2 \\\\ 2 & 4 \\end{pmatrix}$ 的特征值为 ____。", "options": None, "answer": "$\\lambda_{1}=0, \\lambda_{2}=5$", "analysis": "特征方程 $|\\lambda I - A| = \\begin{vmatrix} \\lambda-1 & -2 \\\\ -2 & \\lambda-4 \\end{vmatrix} = (\\lambda-1)(\\lambda-4) - 4 = \\lambda^{2} - 5\\lambda = \\lambda(\\lambda-5) = 0$。故 $\\lambda_{1}=0$，$\\lambda_{2}=5$。", "source": "自建题目", "tags": ["特征值", "特征方程"], "origin": "改编自特征值计算题，元素调整"},
    {"id": "soc_xd_036", "subject": "线代", "type": "选择", "difficulty": 4, "content": "设 $A$ 为 $3$ 阶矩阵，特征值为 $1, -1, 2$，则 $\\text{tr}(A) = $（ ）。", "options": ["A. $2$", "B. $-2$", "C. $0$", "D. $1$"], "answer": "A", "analysis": "矩阵的迹等于特征值之和：$\\text{tr}(A) = 1 + (-1) + 2 = 2$。选 A。", "source": "自建题目", "tags": ["特征值", "矩阵的迹"], "origin": "改编自特征值与迹关系题"},
    {"id": "soc_xd_037", "subject": "线代", "type": "填空", "difficulty": 4, "content": "若 $A$ 相似于对角矩阵 $\\text{diag}(2, 3, 4)$，则 $A^{10}$ 的特征值为 ____。", "options": None, "answer": "$2^{10}, 3^{10}, 4^{10}$", "analysis": "相似矩阵有相同特征值。$A$ 的特征值为 $2, 3, 4$，$A^{10}$ 的特征值为 $2^{10}, 3^{10}, 4^{10}$。", "source": "自建题目", "tags": ["特征值", "相似矩阵", "矩阵幂"], "origin": "改编自相似矩阵特征值题"},
    {"id": "soc_xd_038", "subject": "线代", "type": "选择", "difficulty": 4, "content": "下列矩阵中不能对角化的是（ ）。", "options": ["A. $\\begin{pmatrix} 1 & 0 \\\\ 0 & 2 \\end{pmatrix}$", "B. $\\begin{pmatrix} 1 & 1 \\\\ 0 & 1 \\end{pmatrix}$", "C. $\\begin{pmatrix} 2 & 1 \\\\ 1 & 2 \\end{pmatrix}$", "D. $\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$"], "answer": "B", "analysis": "B 是若尔当块，特征值 $\\lambda=1$（二重），但几何重数 $= 2 - r(I-A) = 2 - 1 = 1 < 2$（代数重数），不能对角化。选 B。", "source": "自建题目", "tags": ["特征值", "对角化", "若尔当块"], "origin": "改编自对角化判别题"},
])

# 二次型 (7道)
questions.extend([
    {"id": "soc_xd_039", "subject": "线代", "type": "填空", "difficulty": 3, "content": "二次型 $f(x, y) = 2x^{2} + 4xy + 3y^{2}$ 的矩阵为 ____。", "options": None, "answer": "$\\begin{pmatrix} 2 & 2 \\\\ 2 & 3 \\end{pmatrix}$", "analysis": "二次型 $f = ax^{2} + 2bxy + cy^{2}$ 的矩阵为 $\\begin{pmatrix} a & b \\\\ b & c \\end{pmatrix}$。这里 $a=2$，$2b=4$ 即 $b=2$，$c=3$。故矩阵为 $\\begin{pmatrix} 2 & 2 \\\\ 2 & 3 \\end{pmatrix}$。", "source": "自建题目", "tags": ["二次型", "二次型矩阵"], "origin": "改编自二次型矩阵题，系数调整"},
    {"id": "soc_xd_040", "subject": "线代", "type": "选择", "difficulty": 3, "content": "二次型 $f = x^{2} + 2y^{2} + 3z^{2} + 2xy$ 的秩为（ ）。", "options": ["A. $1$", "B. $2$", "C. $3$", "D. $0$"], "answer": "C", "analysis": "二次型矩阵 $A = \\begin{pmatrix} 1 & 1 & 0 \\\\ 1 & 2 & 0 \\\\ 0 & 0 & 3 \\end{pmatrix}$。$|A| = 3(2-1) = 3 \\neq 0$，故 $r(A) = 3$。选 C。", "source": "自建题目", "tags": ["二次型", "秩"], "origin": "改编自二次型秩题"},
    {"id": "soc_xd_041", "subject": "线代", "type": "填空", "difficulty": 4, "content": "二次型 $f = 2x^{2} + 5y^{2} + 5z^{2} + 4xy$ 的标准形中平方项系数为 ____。", "options": None, "answer": "$1, 3, 6$（或其他等价形式）", "analysis": "二次型矩阵 $A = \\begin{pmatrix} 2 & 2 & 0 \\\\ 2 & 5 & 0 \\\\ 0 & 0 & 5 \\end{pmatrix}$。特征方程 $|\\lambda I - A| = (\\lambda-5)[(\\lambda-2)(\\lambda-5)-4] = (\\lambda-5)(\\lambda^{2}-7\\lambda+6) = (\\lambda-5)(\\lambda-1)(\\lambda-6) = 0$。特征值 $\\lambda = 1, 5, 6$。标准形 $f = y_{1}^{2} + 5y_{2}^{2} + 6y_{3}^{2}$。", "source": "自建题目", "tags": ["二次型", "标准形", "特征值"], "origin": "改编自二次型标准形题，系数调整"},
    {"id": "soc_xd_042", "subject": "线代", "type": "选择", "difficulty": 4, "content": "二次型 $f = x^{2} + y^{2} + z^{2} - 2xy - 2yz$ 的正惯性指数为（ ）。", "options": ["A. $0$", "B. $1$", "C. $2$", "D. $3$"], "answer": "B", "analysis": "二次型矩阵 $A = \\begin{pmatrix} 1 & -1 & 0 \\\\ -1 & 1 & -1 \\\\ 0 & -1 & 1 \\end{pmatrix}$。特征值为 $0, 1, 2$（计算略），正特征值个数为 $2$。但经配方法：$f = (x-y)^{2} + z^{2} - 2yz = (x-y)^{2} + (z^{2}-2yz+y^{2}) - y^{2} = (x-y)^{2} + (z-y)^{2} - y^{2}$。正惯性指数 $2$，负惯性指数 $1$。选 C。", "source": "自建题目", "tags": ["二次型", "正惯性指数", "配方法"], "origin": "改编自正惯性指数题"},
    {"id": "soc_xd_043", "subject": "线代", "type": "填空", "difficulty": 4, "content": "二次型 $f = 2x^{2} + 2y^{2} + 2z^{2} + 2xy + 2xz + 2yz$ 的规范形为 ____。", "options": None, "answer": "$z_{1}^{2} + z_{2}^{2} + z_{3}^{2}$（正定）", "analysis": "二次型矩阵 $A = \\begin{pmatrix} 2 & 1 & 1 \\\\ 1 & 2 & 1 \\\\ 1 & 1 & 2 \\end{pmatrix}$。特征值为 $1, 1, 4$（全正），故正定，规范形为 $z_{1}^{2} + z_{2}^{2} + z_{3}^{2}$。", "source": "自建题目", "tags": ["二次型", "规范形", "正定"], "origin": "改编自二次型规范形题"},
    {"id": "soc_xd_044", "subject": "线代", "type": "选择", "difficulty": 3, "content": "二次型 $f = x^{2} + 2y^{2} + 3z^{2}$ 的正定性为（ ）。", "options": ["A. 正定", "B. 负定", "C. 不定", "D. 半正定"], "answer": "A", "analysis": "二次型矩阵 $A = \\text{diag}(1, 2, 3)$，所有特征值 $1, 2, 3 > 0$，故正定。选 A。", "source": "自建题目", "tags": ["二次型", "正定"], "origin": "改编自正定判别题"},
    {"id": "soc_xd_045", "subject": "线代", "type": "填空", "difficulty": 4, "content": "若二次型 $f = x^{2} + 2y^{2} + (k-1)z^{2} + 2kxy$ 正定，则 $k$ 的取值范围是 ____。", "options": None, "answer": "$-\\frac{1}{2} < k < 1$", "analysis": "二次型矩阵 $A = \\begin{pmatrix} 1 & k & 0 \\\\ k & 2 & 0 \\\\ 0 & 0 & k-1 \\end{pmatrix}$。正定要求各阶顺序主子式为正：$\\Delta_{1} = 1 > 0$；$\\Delta_{2} = 2 - k^{2} > 0$ 即 $|k| < \\sqrt{2}$；$\\Delta_{3} = (k-1)(2-k^{2}) > 0$。由 $\\Delta_{3} > 0$ 需 $k-1$ 与 $2-k^{2}$ 同号。若 $k > 1$ 则 $2-k^{2} < 0$ 当 $k > \\sqrt{2}$，但 $1 < k < \\sqrt{2}$ 时 $\\Delta_{3} < 0$。若 $k < 1$ 则需 $2-k^{2} < 0$ 即 $k < -\\sqrt{2}$，但此时 $\\Delta_{2} < 0$。重新分析：$\\Delta_{3} = (k-1)(2-k^{2}) > 0$。当 $-\\sqrt{2} < k < 1$ 时 $k-1<0$ 且 $2-k^{2}>0$，$\\Delta_{3}<0$。需更仔细：正定要求 $\\Delta_{3}>0$，即 $(k-1)(2-k^{2})>0$。当 $k>1$ 需 $2-k^{2}>0$ 即 $1<k<\\sqrt{2}$，此时 $\\Delta_{2}=2-k^{2}>0$ 成立。当 $k<1$ 需 $2-k^{2}<0$ 即 $k<-\\sqrt{2}$，但 $\\Delta_{2}<0$ 不满足。综上 $1 < k < \\sqrt{2}$。", "source": "自建题目", "tags": ["二次型", "正定", "顺序主子式"], "origin": "改编自正定参数题"},
])

print(f"线代题目数: {len([q for q in questions if q['subject'] == '线代'])}")

# ========== 概率 45道 ==========
# 概率基础 (12道)
questions.extend([
    {"id": "soc_gl_001", "subject": "概率", "type": "选择", "difficulty": 2, "content": "袋中有 $5$ 个红球，$3$ 个白球，从中任取 $2$ 个，则两个都是红球的概率为（ ）。", "options": ["A. $\\frac{5}{14}$", "B. $\\frac{10}{28}$", "C. $\\frac{25}{64}$", "D. $\\frac{5}{8}$"], "answer": "A", "analysis": "总取法 $C_{8}^{2} = 28$，两个红球取法 $C_{5}^{2} = 10$。概率 $= \\frac{10}{28} = \\frac{5}{14}$。选 A。", "source": "自建题目", "tags": ["概率", "古典概型", "组合"], "origin": "改编自古典概型题，球数调整"},
    {"id": "soc_gl_002", "subject": "概率", "type": "填空", "difficulty": 3, "content": "设 $P(A) = 0.6$，$P(B) = 0.5$，$P(A|B) = 0.8$，则 $P(B|A) = $ ____。", "options": None, "answer": "$\\frac{2}{3}$", "analysis": "由条件概率 $P(A|B) = \\frac{P(AB)}{P(B)}$，故 $P(AB) = 0.8 \\times 0.5 = 0.4$。$P(B|A) = \\frac{P(AB)}{P(A)} = \\frac{0.4}{0.6} = \\frac{2}{3}$。", "source": "自建题目", "tags": ["概率", "条件概率", "贝叶斯公式"], "origin": "改编自条件概率题，数值调整"},
    {"id": "soc_gl_003", "subject": "概率", "type": "选择", "difficulty": 3, "content": "若事件 $A$ 与 $B$ 互斥，$P(A) = 0.3$，$P(B) = 0.4$，则 $P(A \\cup B) = $（ ）。", "options": ["A. $0.7$", "B. $0.12$", "C. $0.3$", "D. $0.4$"], "answer": "A", "analysis": "互斥事件 $P(A \\cup B) = P(A) + P(B) = 0.3 + 0.4 = 0.7$。选 A。", "source": "自建题目", "tags": ["概率", "互斥事件", "加法公式"], "origin": "改编自互斥事件概率题"},
    {"id": "soc_gl_004", "subject": "概率", "type": "填空", "difficulty": 3, "content": "掷两枚骰子，点数之和为 $7$ 的概率为 ____。", "options": None, "answer": "$\\frac{1}{6}$", "analysis": "总结果 $36$ 种。和为 $7$ 的组合：$(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$ 共 $6$ 种。概率 $= \\frac{6}{36} = \\frac{1}{6}$。", "source": "自建题目", "tags": ["概率", "古典概型"], "origin": "改编自骰子概率题"},
    {"id": "soc_gl_005", "subject": "概率", "type": "选择", "difficulty": 3, "content": "若 $A$、$B$ 独立，$P(A) = 0.3$，$P(B) = 0.4$，则 $P(AB) = $（ ）。", "options": ["A. $0.7$", "B. $0.12$", "C. $0.3$", "D. $0.4$"], "answer": "B", "analysis": "独立事件 $P(AB) = P(A) \\cdot P(B) = 0.3 \\times 0.4 = 0.12$。选 B。", "source": "自建题目", "tags": ["概率", "独立性"], "origin": "改编自独立性概率题"},
    {"id": "soc_gl_006", "subject": "概率", "type": "填空", "difficulty": 3, "content": "一批产品 $10$ 件，其中 $3$ 件次品，任取 $2$ 件，至少有一件次品的概率为 ____。", "options": None, "answer": "$\\frac{8}{15}$", "analysis": "对立事件：两件都是正品。$P(\\text{都正品}) = \\frac{C_{7}^{2}}{C_{10}^{2}} = \\frac{21}{45} = \\frac{7}{15}$。$P(\\text{至少一件次品}) = 1 - \\frac{7}{15} = \\frac{8}{15}$。", "source": "自建题目", "tags": ["概率", "古典概型", "对立事件"], "origin": "改编自产品抽样题，数量调整"},
    {"id": "soc_gl_007", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $P(A) = 0.5$，$P(B) = 0.3$，$P(A \\cup B) = 0.6$，则 $P(AB) = $（ ）。", "options": ["A. $0.2$", "B. $0.15$", "C. $0.8$", "D. $0.1$"], "answer": "A", "analysis": "由加法公式 $P(A \\cup B) = P(A) + P(B) - P(AB)$，故 $P(AB) = 0.5 + 0.3 - 0.6 = 0.2$。选 A。", "source": "自建题目", "tags": ["概率", "加法公式"], "origin": "改编自加法公式题"},
    {"id": "soc_gl_008", "subject": "概率", "type": "填空", "difficulty": 4, "content": "某人射击命中率为 $0.8$，连续射击 $3$ 次，恰好命中 $2$ 次的概率为 ____。", "options": None, "answer": "$0.384$", "analysis": "伯努利概型 $P = C_{3}^{2} \\cdot 0.8^{2} \\cdot 0.2^{1} = 3 \\times 0.64 \\times 0.2 = 0.384$。", "source": "自建题目", "tags": ["概率", "伯努利概型", "二项分布"], "origin": "改编自伯努利试验题，命中率和次数调整"},
    {"id": "soc_gl_009", "subject": "概率", "type": "选择", "difficulty": 3, "content": "若 $P(A) > 0$，$P(B) > 0$，且 $A$、$B$ 互斥，则（ ）。", "options": ["A. $A$、$B$ 独立", "B. $A$、$B$ 不独立", "C. $P(A|B) = P(A)$", "D. $P(AB) = P(A)P(B)$"], "answer": "B", "analysis": "互斥且概率均正意味着 $P(AB) = 0 \\neq P(A)P(B)$，故不独立。选 B。", "source": "自建题目", "tags": ["概率", "互斥", "独立性"], "origin": "改编自互斥与独立关系题"},
    {"id": "soc_gl_010", "subject": "概率", "type": "填空", "difficulty": 4, "content": "袋中 $5$ 红 $3$ 白，无放回连取 $2$ 次，第二次取红球的概率为 ____。", "options": None, "answer": "$\\frac{5}{8}$", "analysis": "由全概率公式：$P = \\frac{5}{8} \\cdot \\frac{4}{7} + \\frac{3}{8} \\cdot \\frac{5}{7} = \\frac{20+15}{56} = \\frac{35}{56} = \\frac{5}{8}$。可见与第一次结果无关。", "source": "自建题目", "tags": ["概率", "全概率公式"], "origin": "改编自全概率公式题"},
    {"id": "soc_gl_011", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $A$、$B$ 为随机事件，$P(A) = \\frac{1}{3}$，$P(B) = \\frac{1}{4}$，$P(AB) = \\frac{1}{6}$，则 $P(A|B) = $（ ）。", "options": ["A. $\\frac{1}{2}$", "B. $\\frac{2}{3}$", "C. $\\frac{1}{3}$", "D. $\\frac{1}{4}$"], "answer": "B", "analysis": "$P(A|B) = \\frac{P(AB)}{P(B)} = \\frac{1/6}{1/4} = \\frac{4}{6} = \\frac{2}{3}$。选 B。", "source": "自建题目", "tags": ["概率", "条件概率"], "origin": "改编自条件概率题"},
    {"id": "soc_gl_012", "subject": "概率", "type": "填空", "difficulty": 4, "content": "三封信随机投入四个信箱，则某指定信箱恰有两封信的概率为 ____。", "options": None, "answer": "$\\frac{9}{64}$", "analysis": "每封信独立投入，指定信箱恰两封：$C_{3}^{2} \\cdot (\\frac{1}{4})^{2} \\cdot \\frac{3}{4} = 3 \\cdot \\frac{1}{16} \\cdot \\frac{3}{4} = \\frac{9}{64}$。", "source": "自建题目", "tags": ["概率", "古典概型", "二项分布"], "origin": "改编自信箱问题"},
])

# 随机变量及其分布 (12道)
questions.extend([
    {"id": "soc_gl_013", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设随机变量 $X \\sim B(5, 0.4)$，则 $E(X) = $（ ）。", "options": ["A. $2$", "B. $1.2$", "C. $0.4$", "D. $5$"], "answer": "A", "analysis": "二项分布 $B(n, p)$ 的期望 $E(X) = np = 5 \\times 0.4 = 2$。选 A。", "source": "自建题目", "tags": ["随机变量", "二项分布", "期望"], "origin": "改编自二项分布期望题"},
    {"id": "soc_gl_014", "subject": "概率", "type": "填空", "difficulty": 3, "content": "设 $X \\sim P(\\lambda)$（泊松分布），$E(X) = 3$，则 $D(X) = $ ____。", "options": None, "answer": "$3$", "analysis": "泊松分布 $P(\\lambda)$ 的期望和方差都等于 $\\lambda$，故 $D(X) = \\lambda = 3$。", "source": "自建题目", "tags": ["随机变量", "泊松分布", "方差"], "origin": "改编自泊松分布题"},
    {"id": "soc_gl_015", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $X \\sim N(2, 4)$，则 $D(X) = $（ ）。", "options": ["A. $2$", "B. $4$", "C. $16$", "D. $\\sqrt{2}$"], "answer": "B", "analysis": "正态分布 $N(\\mu, \\sigma^{2})$ 中第二个参数是方差。$X \\sim N(2, 4)$ 表示 $\\mu=2$，$\\sigma^{2}=4$，故 $D(X) = 4$。选 B。", "source": "自建题目", "tags": ["随机变量", "正态分布", "方差"], "origin": "改编自正态分布题"},
    {"id": "soc_gl_016", "subject": "概率", "type": "填空", "difficulty": 3, "content": "设 $X \\sim U[2, 6]$（均匀分布），则 $E(X) = $ ____。", "options": None, "answer": "$4$", "analysis": "均匀分布 $U[a, b]$ 的期望 $E(X) = \\frac{a+b}{2} = \\frac{2+6}{2} = 4$。", "source": "自建题目", "tags": ["随机变量", "均匀分布", "期望"], "origin": "改编自均匀分布题"},
    {"id": "soc_gl_017", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $X \\sim E(2)$（指数分布，参数 $\\lambda=2$），则 $E(X) = $（ ）。", "options": ["A. $2$", "B. $\\frac{1}{2}$", "C. $4$", "D. $\\frac{1}{4}$"], "answer": "B", "analysis": "指数分布 $E(\\lambda)$ 的期望 $E(X) = \\frac{1}{\\lambda} = \\frac{1}{2}$。选 B。", "source": "自建题目", "tags": ["随机变量", "指数分布", "期望"], "origin": "改编自指数分布题"},
    {"id": "soc_gl_018", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X$ 的密度函数 $f(x) = \\begin{cases} 2x, & 0 \\leq x \\leq 1 \\\\ 0, & \\text{其他} \\end{cases}$，则 $P(X > 0.5) = $ ____。", "options": None, "answer": "$\\frac{3}{4}$", "analysis": "$P(X > 0.5) = \\int_{0.5}^{1} 2x \\, dx = [x^{2}]_{0.5}^{1} = 1 - 0.25 = 0.75 = \\frac{3}{4}$。", "source": "自建题目", "tags": ["随机变量", "密度函数", "概率计算"], "origin": "改编自密度函数概率题"},
    {"id": "soc_gl_019", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X \\sim N(0, 1)$，$\\Phi(1) \\approx 0.8413$，则 $P(X < -1) = $（ ）。", "options": ["A. $0.8413$", "B. $0.1587$", "C. $0.5$", "D. $0.3174$"], "answer": "B", "analysis": "标准正态分布对称性 $P(X < -1) = P(X > 1) = 1 - \\Phi(1) = 1 - 0.8413 = 0.1587$。选 B。", "source": "自建题目", "tags": ["随机变量", "正态分布", "对称性"], "origin": "改编自正态分布查表题"},
    {"id": "soc_gl_020", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X$ 的分布函数 $F(x) = \\begin{cases} 0, & x < 0 \\\\ x^{2}, & 0 \\leq x \\leq 1 \\\\ 1, & x > 1 \\end{cases}$，则 $P(0.5 < X < 1.5) = $ ____。", "options": None, "answer": "$\\frac{3}{4}$", "analysis": "$P(0.5 < X < 1.5) = F(1.5) - F(0.5) = 1 - 0.25 = 0.75 = \\frac{3}{4}$。", "source": "自建题目", "tags": ["随机变量", "分布函数"], "origin": "改编自分布函数题"},
    {"id": "soc_gl_021", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $X \\sim B(n, p)$，$E(X) = 6$，$D(X) = 3$，则 $p = $（ ）。", "options": ["A. $0.5$", "B. $0.3$", "C. $0.6$", "D. $0.4$"], "answer": "A", "analysis": "$E(X) = np = 6$，$D(X) = np(1-p) = 3$。$\\frac{D}{E} = 1-p = \\frac{1}{2}$，故 $p = 0.5$。选 A。", "source": "自建题目", "tags": ["随机变量", "二项分布", "期望", "方差"], "origin": "改编自二项分布参数题"},
    {"id": "soc_gl_022", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X$ 的密度 $f(x) = ce^{-2x}$（$x > 0$），则常数 $c = $ ____。", "options": None, "answer": "$2$", "analysis": "由 $\\int_{0}^{\\infty} ce^{-2x} \\, dx = 1$，$c \\cdot \\frac{1}{2} = 1$，故 $c = 2$。", "source": "自建题目", "tags": ["随机变量", "密度函数", "归一化"], "origin": "改编自密度函数常数题"},
    {"id": "soc_gl_023", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X \\sim N(\\mu, \\sigma^{2})$，$P(X < \\mu - \\sigma) = $（ ）。", "options": ["A. $0.1587$", "B. $0.8413$", "C. $0.0228$", "D. $0.5$"], "answer": "A", "analysis": "$P(X < \\mu - \\sigma) = P\\left(\\frac{X-\\mu}{\\sigma} < -1\\right) = \\Phi(-1) = 1 - \\Phi(1) \\approx 0.1587$。选 A。", "source": "自建题目", "tags": ["随机变量", "正态分布", "标准化"], "origin": "改编自正态分布标准化题"},
    {"id": "soc_gl_024", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X \\sim U[0, 2]$，则 $E(X^{2}) = $ ____。", "options": None, "answer": "$\\frac{4}{3}$", "analysis": "$E(X^{2}) = \\int_{0}^{2} x^{2} \\cdot \\frac{1}{2} \\, dx = \\frac{1}{2} \\cdot \\frac{x^{3}}{3}\\Big|_{0}^{2} = \\frac{1}{2} \\cdot \\frac{8}{3} = \\frac{4}{3}$。", "source": "自建题目", "tags": ["随机变量", "均匀分布", "期望"], "origin": "改编自均匀分布期望题"},
])

# 数字特征 (12道)
questions.extend([
    {"id": "soc_gl_025", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $E(X) = 2$，$D(X) = 4$，则 $E(X^{2}) = $（ ）。", "options": ["A. $6$", "B. $8$", "C. $4$", "D. $2$"], "answer": "B", "analysis": "$E(X^{2}) = D(X) + [E(X)]^{2} = 4 + 4 = 8$。选 B。", "source": "自建题目", "tags": ["数字特征", "期望", "方差"], "origin": "改编自期望方差关系题"},
    {"id": "soc_gl_026", "subject": "概率", "type": "填空", "difficulty": 3, "content": "设 $X$、$Y$ 独立，$D(X) = 2$，$D(Y) = 3$，则 $D(X + Y) = $ ____。", "options": None, "answer": "$5$", "analysis": "独立随机变量 $D(X+Y) = D(X) + D(Y) = 2 + 3 = 5$。", "source": "自建题目", "tags": ["数字特征", "方差", "独立性"], "origin": "改编自方差和题"},
    {"id": "soc_gl_027", "subject": "概率", "type": "选择", "difficulty": 3, "content": "设 $E(X) = 1$，$E(Y) = 2$，则 $E(2X + 3Y) = $（ ）。", "options": ["A. $5$", "B. $7$", "C. $8$", "D. $6$"], "answer": "C", "analysis": "由期望线性性 $E(2X + 3Y) = 2E(X) + 3E(Y) = 2 + 6 = 8$。选 C。", "source": "自建题目", "tags": ["数字特征", "期望", "线性性"], "origin": "改编自期望线性性题"},
    {"id": "soc_gl_028", "subject": "概率", "type": "填空", "difficulty": 3, "content": "设 $D(X) = 4$，则 $D(3X + 1) = $ ____。", "options": None, "answer": "$36$", "analysis": "$D(aX + b) = a^{2}D(X)$。$D(3X+1) = 9 \\times 4 = 36$。", "source": "自建题目", "tags": ["数字特征", "方差", "线性变换"], "origin": "改编自方差线性变换题"},
    {"id": "soc_gl_029", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X$、$Y$ 独立，$X \\sim N(1, 4)$，$Y \\sim N(2, 9)$，则 $X + Y \\sim $（ ）。", "options": ["A. $N(3, 13)$", "B. $N(3, 5)$", "C. $N(3, 6.5)$", "D. $N(2, 13)$"], "answer": "A", "analysis": "独立正态变量之和仍正态：$E(X+Y) = 1+2 = 3$，$D(X+Y) = 4+9 = 13$。故 $X+Y \\sim N(3, 13)$。选 A。", "source": "自建题目", "tags": ["数字特征", "正态分布", "独立性"], "origin": "改编自正态分布可加性题"},
    {"id": "soc_gl_030", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $\\text{Cov}(X, Y) = 2$，$D(X) = 4$，$D(Y) = 9$，则 $\\rho_{XY} = $ ____。", "options": None, "answer": "$\\frac{1}{3}$", "analysis": "相关系数 $\\rho_{XY} = \\frac{\\text{Cov}(X,Y)}{\\sqrt{D(X) \\cdot D(Y)}} = \\frac{2}{\\sqrt{4 \\times 9}} = \\frac{2}{6} = \\frac{1}{3}$。", "source": "自建题目", "tags": ["数字特征", "协方差", "相关系数"], "origin": "改编自相关系数题"},
    {"id": "soc_gl_031", "subject": "概率", "type": "选择", "difficulty": 3, "content": "若 $X$、$Y$ 独立，则 $\\text{Cov}(X, Y) = $（ ）。", "options": ["A. $1$", "B. $0$", "C. $E(X)E(Y)$", "D. $-1$"], "answer": "B", "analysis": "独立则不相关，$\\text{Cov}(X, Y) = E(XY) - E(X)E(Y) = 0$。选 B。", "source": "自建题目", "tags": ["数字特征", "协方差", "独立性"], "origin": "改编自独立与协方差题"},
    {"id": "soc_gl_032", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X \\sim B(10, 0.3)$，则 $E(X^{2}) = $ ____。", "options": None, "answer": "$11.1$", "analysis": "$E(X) = np = 3$，$D(X) = np(1-p) = 2.1$。$E(X^{2}) = D(X) + [E(X)]^{2} = 2.1 + 9 = 11.1$。", "source": "自建题目", "tags": ["数字特征", "二项分布", "期望", "方差"], "origin": "改编自二项分布数字特征题"},
    {"id": "soc_gl_033", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X \\sim U[0, 2]$，则 $D(X) = $（ ）。", "options": ["A. $1$", "B. $\\frac{1}{3}$", "C. $\\frac{2}{3}$", "D. $\\frac{1}{2}$"], "answer": "B", "analysis": "均匀分布 $U[a,b]$ 的方差 $D(X) = \\frac{(b-a)^{2}}{12} = \\frac{4}{12} = \\frac{1}{3}$。选 B。", "source": "自建题目", "tags": ["数字特征", "均匀分布", "方差"], "origin": "改编自均匀分布方差题"},
    {"id": "soc_gl_034", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X$、$Y$ 不独立，$D(X) = 1$，$D(Y) = 4$，$\\text{Cov}(X,Y) = 1$，则 $D(X - Y) = $ ____。", "options": None, "answer": "$3$", "analysis": "$D(X - Y) = D(X) + D(Y) - 2\\text{Cov}(X,Y) = 1 + 4 - 2 = 3$。", "source": "自建题目", "tags": ["数字特征", "方差", "协方差"], "origin": "改编自方差差题"},
    {"id": "soc_gl_035", "subject": "概率", "type": "选择", "difficulty": 4, "content": "若 $\\rho_{XY} = 0$，则下列正确的是（ ）。", "options": ["A. $X$、$Y$ 独立", "B. $X$、$Y$ 不独立", "C. $X$、$Y$ 不相关", "D. $X$、$Y$ 线性相关"], "answer": "C", "analysis": "$\\rho_{XY} = 0$ 表示 $X$、$Y$ 不相关（无线性关系），但不一定独立。选 C。", "source": "自建题目", "tags": ["数字特征", "相关系数", "不相关"], "origin": "改编自相关系数性质题"},
    {"id": "soc_gl_036", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X \\sim E(3)$（指数分布），则 $E(X^{2}) = $ ____。", "options": None, "answer": "$\\frac{2}{9}$", "analysis": "$E(X) = \\frac{1}{3}$，$D(X) = \\frac{1}{9}$。$E(X^{2}) = D(X) + [E(X)]^{2} = \\frac{1}{9} + \\frac{1}{9} = \\frac{2}{9}$。", "source": "自建题目", "tags": ["数字特征", "指数分布", "期望", "方差"], "origin": "改编自指数分布数字特征题"},
])

# 大数定律与中心极限定理 (9道)
questions.extend([
    {"id": "soc_gl_037", "subject": "概率", "type": "选择", "difficulty": 3, "content": "切比雪夫不等式 $P(|X - E(X)| \\geq \\epsilon) \\leq $（ ）。", "options": ["A. $\\frac{D(X)}{\\epsilon^{2}}$", "B. $\\frac{D(X)}{\\epsilon}$", "C. $\\frac{\\epsilon}{D(X)}$", "D. $\\frac{\\epsilon^{2}}{D(X)}$"], "answer": "A", "analysis": "切比雪夫不等式 $P(|X - E(X)| \\geq \\epsilon) \\leq \\frac{D(X)}{\\epsilon^{2}}$。选 A。", "source": "自建题目", "tags": ["大数定律", "切比雪夫不等式"], "origin": "改编自切比雪夫不等式题"},
    {"id": "soc_gl_038", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X_{1}, X_{2}, \\ldots, X_{100}$ 独立同分布，$E(X_{i}) = 1$，$D(X_{i}) = 4$，由切比雪夫不等式 $P(|\\bar{X} - 1| \\geq 0.2) \\leq $ ____。", "options": None, "answer": "$1$", "analysis": "$E(\\bar{X}) = 1$，$D(\\bar{X}) = \\frac{4}{100} = 0.04$。切比雪夫：$P(|\\bar{X} - 1| \\geq 0.2) \\leq \\frac{0.04}{0.04} = 1$。", "source": "自建题目", "tags": ["大数定律", "切比雪夫不等式"], "origin": "改编自切比雪夫不等式应用题"},
    {"id": "soc_gl_039", "subject": "概率", "type": "选择", "difficulty": 3, "content": "辛钦大数定律要求随机变量序列（ ）。", "options": ["A. 独立同分布且期望存在", "B. 仅需独立", "C. 仅需同分布", "D. 独立且方差存在"], "answer": "A", "analysis": "辛钦大数定律：$X_{1}, X_{2}, \\ldots$ 独立同分布且期望 $\\mu$ 存在，则 $\\bar{X} \\xrightarrow{P} \\mu$。选 A。", "source": "自建题目", "tags": ["大数定律", "辛钦大数定律"], "origin": "改编自辛钦大数定律题"},
    {"id": "soc_gl_040", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X_{1}, \\ldots, X_{n}$ 独立同分布，$X_{i} \\sim N(2, 4)$，则 $\\sum_{i=1}^{n} X_{i} \\sim $ ____。", "options": None, "answer": "$N(2n, 4n)$", "analysis": "独立正态变量之和仍正态。$E(\\sum X_{i}) = 2n$，$D(\\sum X_{i}) = 4n$。故 $\\sum X_{i} \\sim N(2n, 4n)$。", "source": "自建题目", "tags": ["中心极限定理", "正态分布", "可加性"], "origin": "改编自正态分布可加性题"},
    {"id": "soc_gl_041", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X_{1}, \\ldots, X_{100}$ 独立同分布，$E(X_{i}) = 2$，$D(X_{i}) = 1$，由中心极限定理 $P(\\sum X_{i} > 210) \\approx $（ ）。", "options": ["A. $\\Phi(1)$", "B. $\\Phi(-1)$", "C. $1 - \\Phi(1)$", "D. $\\Phi(0)$"], "answer": "C", "analysis": "$E(\\sum X_{i}) = 200$，$D(\\sum X_{i}) = 100$，$\\sigma = 10$。$P(\\sum X_{i} > 210) = P\\left(\\frac{\\sum X_{i} - 200}{10} > 1\\right) = 1 - \\Phi(1)$。选 C。", "source": "自建题目", "tags": ["中心极限定理", "正态近似"], "origin": "改编自中心极限定理应用题"},
    {"id": "soc_gl_042", "subject": "概率", "type": "填空", "difficulty": 4, "content": "伯努利大数定律：设 $n_{A}$ 为 $n$ 次独立试验中事件 $A$ 发生次数，$p = P(A)$，则 $\\frac{n_{A}}{n} \\xrightarrow{P} $ ____。", "options": None, "answer": "$p$", "analysis": "伯努利大数定律：频率依概率收敛于概率，即 $\\frac{n_{A}}{n} \\xrightarrow{P} p$。", "source": "自建题目", "tags": ["大数定律", "伯努利大数定律"], "origin": "改编自伯努利大数定律题"},
    {"id": "soc_gl_043", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X_{1}, \\ldots, X_{50}$ 独立同分布，$E(X_{i}) = 1$，$D(X_{i}) = 4$，则由中心极限定理 $\\bar{X}$ 近似服从（ ）。", "options": ["A. $N(1, \\frac{4}{50})$", "B. $N(50, 4)$", "C. $N(1, 4)$", "D. $N(50, \\frac{4}{50})$"], "answer": "A", "analysis": "$E(\\bar{X}) = 1$，$D(\\bar{X}) = \\frac{4}{50}$。由中心极限定理 $\\bar{X} \\dot{\\sim} N(1, \\frac{4}{50})$。选 A。", "source": "自建题目", "tags": ["中心极限定理", "样本均值"], "origin": "改编自中心极限定理题"},
    {"id": "soc_gl_044", "subject": "概率", "type": "填空", "difficulty": 4, "content": "设 $X \\sim N(10, 4)$，则 $P(X > 14) \\approx $ ____（用 $\\Phi$ 表示）。", "options": None, "answer": "$1 - \\Phi(2) \\approx 0.0228$", "analysis": "$P(X > 14) = P\\left(\\frac{X-10}{2} > 2\\right) = 1 - \\Phi(2) \\approx 0.0228$。", "source": "自建题目", "tags": ["正态分布", "标准化"], "origin": "改编自正态分布概率题"},
    {"id": "soc_gl_045", "subject": "概率", "type": "选择", "difficulty": 4, "content": "设 $X_{1}, \\ldots, X_{n}$ 独立同分布，$E(X_{i}) = \\mu$，$D(X_{i}) = \\sigma^{2}$，则当 $n$ 充分大时 $\\frac{\\sum X_{i} - n\\mu}{\\sigma\\sqrt{n}}$ 近似服从（ ）。", "options": ["A. $N(0, 1)$", "B. $N(\\mu, \\sigma^{2})$", "C. $N(n\\mu, n\\sigma^{2})$", "D. $U[0, 1]$"], "answer": "A", "analysis": "中心极限定理：$\\frac{\\sum X_{i} - n\\mu}{\\sigma\\sqrt{n}} \\xrightarrow{d} N(0, 1)$。选 A。", "source": "自建题目", "tags": ["中心极限定理", "标准化"], "origin": "改编自中心极限定理标准形式题"},
])

print(f"概率题目数: {len([q for q in questions if q['subject'] == '概率'])}")
print(f"总题目数: {len(questions)}")

# 写入文件
with open("/Users/wuyangcj/trae/回甘demo/collected_social_questions.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"已写入 {len(questions)} 道题目到 collected_social_questions.json")
